FROM golang:alpine
ENV GOPATH=/go

RUN apk update
RUN apk add build-base
RUN apk add git bash

ADD . /go/src/github.com/domino14/word_db_server
WORKDIR /go/src/github.com/domino14/word_db_server

RUN cd cmd/dbmaker && go build
