// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: wordvault/api.proto

package wordvaultconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	wordvault "github.com/domino14/word_db_server/rpc/api/wordvault"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WordVaultServiceName is the fully-qualified name of the WordVaultService service.
	WordVaultServiceName = "wordvault.WordVaultService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WordVaultServiceGetCardInformationProcedure is the fully-qualified name of the WordVaultService's
	// GetCardInformation RPC.
	WordVaultServiceGetCardInformationProcedure = "/wordvault.WordVaultService/GetCardInformation"
	// WordVaultServiceGetNextScheduledProcedure is the fully-qualified name of the WordVaultService's
	// GetNextScheduled RPC.
	WordVaultServiceGetNextScheduledProcedure = "/wordvault.WordVaultService/GetNextScheduled"
	// WordVaultServiceScoreCardProcedure is the fully-qualified name of the WordVaultService's
	// ScoreCard RPC.
	WordVaultServiceScoreCardProcedure = "/wordvault.WordVaultService/ScoreCard"
	// WordVaultServiceEditLastScoreProcedure is the fully-qualified name of the WordVaultService's
	// EditLastScore RPC.
	WordVaultServiceEditLastScoreProcedure = "/wordvault.WordVaultService/EditLastScore"
	// WordVaultServiceAddCardProcedure is the fully-qualified name of the WordVaultService's AddCard
	// RPC.
	WordVaultServiceAddCardProcedure = "/wordvault.WordVaultService/AddCard"
	// WordVaultServiceAddCardsProcedure is the fully-qualified name of the WordVaultService's AddCards
	// RPC.
	WordVaultServiceAddCardsProcedure = "/wordvault.WordVaultService/AddCards"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	wordVaultServiceServiceDescriptor                  = wordvault.File_wordvault_api_proto.Services().ByName("WordVaultService")
	wordVaultServiceGetCardInformationMethodDescriptor = wordVaultServiceServiceDescriptor.Methods().ByName("GetCardInformation")
	wordVaultServiceGetNextScheduledMethodDescriptor   = wordVaultServiceServiceDescriptor.Methods().ByName("GetNextScheduled")
	wordVaultServiceScoreCardMethodDescriptor          = wordVaultServiceServiceDescriptor.Methods().ByName("ScoreCard")
	wordVaultServiceEditLastScoreMethodDescriptor      = wordVaultServiceServiceDescriptor.Methods().ByName("EditLastScore")
	wordVaultServiceAddCardMethodDescriptor            = wordVaultServiceServiceDescriptor.Methods().ByName("AddCard")
	wordVaultServiceAddCardsMethodDescriptor           = wordVaultServiceServiceDescriptor.Methods().ByName("AddCards")
)

// WordVaultServiceClient is a client for the wordvault.WordVaultService service.
type WordVaultServiceClient interface {
	GetCardInformation(context.Context, *connect.Request[wordvault.GetCardInfoRequest]) (*connect.Response[wordvault.Cards], error)
	GetNextScheduled(context.Context, *connect.Request[wordvault.GetNextScheduledRequest]) (*connect.Response[wordvault.Cards], error)
	ScoreCard(context.Context, *connect.Request[wordvault.ScoreCardRequest]) (*connect.Response[wordvault.ScoreCardResponse], error)
	EditLastScore(context.Context, *connect.Request[wordvault.EditLastScoreRequest]) (*connect.Response[wordvault.ScoreCardResponse], error)
	AddCard(context.Context, *connect.Request[wordvault.AddCardRequest]) (*connect.Response[wordvault.AddCardResponse], error)
	AddCards(context.Context, *connect.Request[wordvault.AddCardsRequest]) (*connect.Response[wordvault.AddCardsResponse], error)
}

// NewWordVaultServiceClient constructs a client for the wordvault.WordVaultService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWordVaultServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WordVaultServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &wordVaultServiceClient{
		getCardInformation: connect.NewClient[wordvault.GetCardInfoRequest, wordvault.Cards](
			httpClient,
			baseURL+WordVaultServiceGetCardInformationProcedure,
			connect.WithSchema(wordVaultServiceGetCardInformationMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getNextScheduled: connect.NewClient[wordvault.GetNextScheduledRequest, wordvault.Cards](
			httpClient,
			baseURL+WordVaultServiceGetNextScheduledProcedure,
			connect.WithSchema(wordVaultServiceGetNextScheduledMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		scoreCard: connect.NewClient[wordvault.ScoreCardRequest, wordvault.ScoreCardResponse](
			httpClient,
			baseURL+WordVaultServiceScoreCardProcedure,
			connect.WithSchema(wordVaultServiceScoreCardMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		editLastScore: connect.NewClient[wordvault.EditLastScoreRequest, wordvault.ScoreCardResponse](
			httpClient,
			baseURL+WordVaultServiceEditLastScoreProcedure,
			connect.WithSchema(wordVaultServiceEditLastScoreMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		addCard: connect.NewClient[wordvault.AddCardRequest, wordvault.AddCardResponse](
			httpClient,
			baseURL+WordVaultServiceAddCardProcedure,
			connect.WithSchema(wordVaultServiceAddCardMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		addCards: connect.NewClient[wordvault.AddCardsRequest, wordvault.AddCardsResponse](
			httpClient,
			baseURL+WordVaultServiceAddCardsProcedure,
			connect.WithSchema(wordVaultServiceAddCardsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// wordVaultServiceClient implements WordVaultServiceClient.
type wordVaultServiceClient struct {
	getCardInformation *connect.Client[wordvault.GetCardInfoRequest, wordvault.Cards]
	getNextScheduled   *connect.Client[wordvault.GetNextScheduledRequest, wordvault.Cards]
	scoreCard          *connect.Client[wordvault.ScoreCardRequest, wordvault.ScoreCardResponse]
	editLastScore      *connect.Client[wordvault.EditLastScoreRequest, wordvault.ScoreCardResponse]
	addCard            *connect.Client[wordvault.AddCardRequest, wordvault.AddCardResponse]
	addCards           *connect.Client[wordvault.AddCardsRequest, wordvault.AddCardsResponse]
}

// GetCardInformation calls wordvault.WordVaultService.GetCardInformation.
func (c *wordVaultServiceClient) GetCardInformation(ctx context.Context, req *connect.Request[wordvault.GetCardInfoRequest]) (*connect.Response[wordvault.Cards], error) {
	return c.getCardInformation.CallUnary(ctx, req)
}

// GetNextScheduled calls wordvault.WordVaultService.GetNextScheduled.
func (c *wordVaultServiceClient) GetNextScheduled(ctx context.Context, req *connect.Request[wordvault.GetNextScheduledRequest]) (*connect.Response[wordvault.Cards], error) {
	return c.getNextScheduled.CallUnary(ctx, req)
}

// ScoreCard calls wordvault.WordVaultService.ScoreCard.
func (c *wordVaultServiceClient) ScoreCard(ctx context.Context, req *connect.Request[wordvault.ScoreCardRequest]) (*connect.Response[wordvault.ScoreCardResponse], error) {
	return c.scoreCard.CallUnary(ctx, req)
}

// EditLastScore calls wordvault.WordVaultService.EditLastScore.
func (c *wordVaultServiceClient) EditLastScore(ctx context.Context, req *connect.Request[wordvault.EditLastScoreRequest]) (*connect.Response[wordvault.ScoreCardResponse], error) {
	return c.editLastScore.CallUnary(ctx, req)
}

// AddCard calls wordvault.WordVaultService.AddCard.
func (c *wordVaultServiceClient) AddCard(ctx context.Context, req *connect.Request[wordvault.AddCardRequest]) (*connect.Response[wordvault.AddCardResponse], error) {
	return c.addCard.CallUnary(ctx, req)
}

// AddCards calls wordvault.WordVaultService.AddCards.
func (c *wordVaultServiceClient) AddCards(ctx context.Context, req *connect.Request[wordvault.AddCardsRequest]) (*connect.Response[wordvault.AddCardsResponse], error) {
	return c.addCards.CallUnary(ctx, req)
}

// WordVaultServiceHandler is an implementation of the wordvault.WordVaultService service.
type WordVaultServiceHandler interface {
	GetCardInformation(context.Context, *connect.Request[wordvault.GetCardInfoRequest]) (*connect.Response[wordvault.Cards], error)
	GetNextScheduled(context.Context, *connect.Request[wordvault.GetNextScheduledRequest]) (*connect.Response[wordvault.Cards], error)
	ScoreCard(context.Context, *connect.Request[wordvault.ScoreCardRequest]) (*connect.Response[wordvault.ScoreCardResponse], error)
	EditLastScore(context.Context, *connect.Request[wordvault.EditLastScoreRequest]) (*connect.Response[wordvault.ScoreCardResponse], error)
	AddCard(context.Context, *connect.Request[wordvault.AddCardRequest]) (*connect.Response[wordvault.AddCardResponse], error)
	AddCards(context.Context, *connect.Request[wordvault.AddCardsRequest]) (*connect.Response[wordvault.AddCardsResponse], error)
}

// NewWordVaultServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWordVaultServiceHandler(svc WordVaultServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	wordVaultServiceGetCardInformationHandler := connect.NewUnaryHandler(
		WordVaultServiceGetCardInformationProcedure,
		svc.GetCardInformation,
		connect.WithSchema(wordVaultServiceGetCardInformationMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceGetNextScheduledHandler := connect.NewUnaryHandler(
		WordVaultServiceGetNextScheduledProcedure,
		svc.GetNextScheduled,
		connect.WithSchema(wordVaultServiceGetNextScheduledMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceScoreCardHandler := connect.NewUnaryHandler(
		WordVaultServiceScoreCardProcedure,
		svc.ScoreCard,
		connect.WithSchema(wordVaultServiceScoreCardMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceEditLastScoreHandler := connect.NewUnaryHandler(
		WordVaultServiceEditLastScoreProcedure,
		svc.EditLastScore,
		connect.WithSchema(wordVaultServiceEditLastScoreMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceAddCardHandler := connect.NewUnaryHandler(
		WordVaultServiceAddCardProcedure,
		svc.AddCard,
		connect.WithSchema(wordVaultServiceAddCardMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceAddCardsHandler := connect.NewUnaryHandler(
		WordVaultServiceAddCardsProcedure,
		svc.AddCards,
		connect.WithSchema(wordVaultServiceAddCardsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/wordvault.WordVaultService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WordVaultServiceGetCardInformationProcedure:
			wordVaultServiceGetCardInformationHandler.ServeHTTP(w, r)
		case WordVaultServiceGetNextScheduledProcedure:
			wordVaultServiceGetNextScheduledHandler.ServeHTTP(w, r)
		case WordVaultServiceScoreCardProcedure:
			wordVaultServiceScoreCardHandler.ServeHTTP(w, r)
		case WordVaultServiceEditLastScoreProcedure:
			wordVaultServiceEditLastScoreHandler.ServeHTTP(w, r)
		case WordVaultServiceAddCardProcedure:
			wordVaultServiceAddCardHandler.ServeHTTP(w, r)
		case WordVaultServiceAddCardsProcedure:
			wordVaultServiceAddCardsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWordVaultServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWordVaultServiceHandler struct{}

func (UnimplementedWordVaultServiceHandler) GetCardInformation(context.Context, *connect.Request[wordvault.GetCardInfoRequest]) (*connect.Response[wordvault.Cards], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.GetCardInformation is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) GetNextScheduled(context.Context, *connect.Request[wordvault.GetNextScheduledRequest]) (*connect.Response[wordvault.Cards], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.GetNextScheduled is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) ScoreCard(context.Context, *connect.Request[wordvault.ScoreCardRequest]) (*connect.Response[wordvault.ScoreCardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.ScoreCard is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) EditLastScore(context.Context, *connect.Request[wordvault.EditLastScoreRequest]) (*connect.Response[wordvault.ScoreCardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.EditLastScore is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) AddCard(context.Context, *connect.Request[wordvault.AddCardRequest]) (*connect.Response[wordvault.AddCardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.AddCard is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) AddCards(context.Context, *connect.Request[wordvault.AddCardsRequest]) (*connect.Response[wordvault.AddCardsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.AddCards is not implemented"))
}
