// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: rpc/wordvault/api.proto

package wordvaultconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	wordvault "github.com/domino14/word_db_server/api/rpc/wordvault"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WordVaultServiceName is the fully-qualified name of the WordVaultService service.
	WordVaultServiceName = "wordvault.WordVaultService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WordVaultServiceGetCardCountProcedure is the fully-qualified name of the WordVaultService's
	// GetCardCount RPC.
	WordVaultServiceGetCardCountProcedure = "/wordvault.WordVaultService/GetCardCount"
	// WordVaultServiceGetCardCountByDeckProcedure is the fully-qualified name of the WordVaultService's
	// GetCardCountByDeck RPC.
	WordVaultServiceGetCardCountByDeckProcedure = "/wordvault.WordVaultService/GetCardCountByDeck"
	// WordVaultServiceGetCardInformationProcedure is the fully-qualified name of the WordVaultService's
	// GetCardInformation RPC.
	WordVaultServiceGetCardInformationProcedure = "/wordvault.WordVaultService/GetCardInformation"
	// WordVaultServiceGetNextScheduledProcedure is the fully-qualified name of the WordVaultService's
	// GetNextScheduled RPC.
	WordVaultServiceGetNextScheduledProcedure = "/wordvault.WordVaultService/GetNextScheduled"
	// WordVaultServiceGetSingleNextScheduledProcedure is the fully-qualified name of the
	// WordVaultService's GetSingleNextScheduled RPC.
	WordVaultServiceGetSingleNextScheduledProcedure = "/wordvault.WordVaultService/GetSingleNextScheduled"
	// WordVaultServiceNextScheduledCountProcedure is the fully-qualified name of the WordVaultService's
	// NextScheduledCount RPC.
	WordVaultServiceNextScheduledCountProcedure = "/wordvault.WordVaultService/NextScheduledCount"
	// WordVaultServiceNextScheduledCountByDeckProcedure is the fully-qualified name of the
	// WordVaultService's NextScheduledCountByDeck RPC.
	WordVaultServiceNextScheduledCountByDeckProcedure = "/wordvault.WordVaultService/NextScheduledCountByDeck"
	// WordVaultServiceScoreCardProcedure is the fully-qualified name of the WordVaultService's
	// ScoreCard RPC.
	WordVaultServiceScoreCardProcedure = "/wordvault.WordVaultService/ScoreCard"
	// WordVaultServiceEditLastScoreProcedure is the fully-qualified name of the WordVaultService's
	// EditLastScore RPC.
	WordVaultServiceEditLastScoreProcedure = "/wordvault.WordVaultService/EditLastScore"
	// WordVaultServiceAddCardsProcedure is the fully-qualified name of the WordVaultService's AddCards
	// RPC.
	WordVaultServiceAddCardsProcedure = "/wordvault.WordVaultService/AddCards"
	// WordVaultServiceMoveCardsProcedure is the fully-qualified name of the WordVaultService's
	// MoveCards RPC.
	WordVaultServiceMoveCardsProcedure = "/wordvault.WordVaultService/MoveCards"
	// WordVaultServicePostponeProcedure is the fully-qualified name of the WordVaultService's Postpone
	// RPC.
	WordVaultServicePostponeProcedure = "/wordvault.WordVaultService/Postpone"
	// WordVaultServiceDeleteProcedure is the fully-qualified name of the WordVaultService's Delete RPC.
	WordVaultServiceDeleteProcedure = "/wordvault.WordVaultService/Delete"
	// WordVaultServiceDeleteFromDeckProcedure is the fully-qualified name of the WordVaultService's
	// DeleteFromDeck RPC.
	WordVaultServiceDeleteFromDeckProcedure = "/wordvault.WordVaultService/DeleteFromDeck"
	// WordVaultServiceGetDailyProgressProcedure is the fully-qualified name of the WordVaultService's
	// GetDailyProgress RPC.
	WordVaultServiceGetDailyProgressProcedure = "/wordvault.WordVaultService/GetDailyProgress"
	// WordVaultServiceGetDailyProgressByDeckProcedure is the fully-qualified name of the
	// WordVaultService's GetDailyProgressByDeck RPC.
	WordVaultServiceGetDailyProgressByDeckProcedure = "/wordvault.WordVaultService/GetDailyProgressByDeck"
	// WordVaultServiceGetDailyLeaderboardProcedure is the fully-qualified name of the
	// WordVaultService's GetDailyLeaderboard RPC.
	WordVaultServiceGetDailyLeaderboardProcedure = "/wordvault.WordVaultService/GetDailyLeaderboard"
	// WordVaultServiceAddDeckProcedure is the fully-qualified name of the WordVaultService's AddDeck
	// RPC.
	WordVaultServiceAddDeckProcedure = "/wordvault.WordVaultService/AddDeck"
	// WordVaultServiceGetDecksProcedure is the fully-qualified name of the WordVaultService's GetDecks
	// RPC.
	WordVaultServiceGetDecksProcedure = "/wordvault.WordVaultService/GetDecks"
	// WordVaultServiceEditDeckProcedure is the fully-qualified name of the WordVaultService's EditDeck
	// RPC.
	WordVaultServiceEditDeckProcedure = "/wordvault.WordVaultService/EditDeck"
	// WordVaultServiceDeleteDeckProcedure is the fully-qualified name of the WordVaultService's
	// DeleteDeck RPC.
	WordVaultServiceDeleteDeckProcedure = "/wordvault.WordVaultService/DeleteDeck"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	wordVaultServiceServiceDescriptor                        = wordvault.File_rpc_wordvault_api_proto.Services().ByName("WordVaultService")
	wordVaultServiceGetCardCountMethodDescriptor             = wordVaultServiceServiceDescriptor.Methods().ByName("GetCardCount")
	wordVaultServiceGetCardCountByDeckMethodDescriptor       = wordVaultServiceServiceDescriptor.Methods().ByName("GetCardCountByDeck")
	wordVaultServiceGetCardInformationMethodDescriptor       = wordVaultServiceServiceDescriptor.Methods().ByName("GetCardInformation")
	wordVaultServiceGetNextScheduledMethodDescriptor         = wordVaultServiceServiceDescriptor.Methods().ByName("GetNextScheduled")
	wordVaultServiceGetSingleNextScheduledMethodDescriptor   = wordVaultServiceServiceDescriptor.Methods().ByName("GetSingleNextScheduled")
	wordVaultServiceNextScheduledCountMethodDescriptor       = wordVaultServiceServiceDescriptor.Methods().ByName("NextScheduledCount")
	wordVaultServiceNextScheduledCountByDeckMethodDescriptor = wordVaultServiceServiceDescriptor.Methods().ByName("NextScheduledCountByDeck")
	wordVaultServiceScoreCardMethodDescriptor                = wordVaultServiceServiceDescriptor.Methods().ByName("ScoreCard")
	wordVaultServiceEditLastScoreMethodDescriptor            = wordVaultServiceServiceDescriptor.Methods().ByName("EditLastScore")
	wordVaultServiceAddCardsMethodDescriptor                 = wordVaultServiceServiceDescriptor.Methods().ByName("AddCards")
	wordVaultServiceMoveCardsMethodDescriptor                = wordVaultServiceServiceDescriptor.Methods().ByName("MoveCards")
	wordVaultServicePostponeMethodDescriptor                 = wordVaultServiceServiceDescriptor.Methods().ByName("Postpone")
	wordVaultServiceDeleteMethodDescriptor                   = wordVaultServiceServiceDescriptor.Methods().ByName("Delete")
	wordVaultServiceDeleteFromDeckMethodDescriptor           = wordVaultServiceServiceDescriptor.Methods().ByName("DeleteFromDeck")
	wordVaultServiceGetDailyProgressMethodDescriptor         = wordVaultServiceServiceDescriptor.Methods().ByName("GetDailyProgress")
	wordVaultServiceGetDailyProgressByDeckMethodDescriptor   = wordVaultServiceServiceDescriptor.Methods().ByName("GetDailyProgressByDeck")
	wordVaultServiceGetDailyLeaderboardMethodDescriptor      = wordVaultServiceServiceDescriptor.Methods().ByName("GetDailyLeaderboard")
	wordVaultServiceAddDeckMethodDescriptor                  = wordVaultServiceServiceDescriptor.Methods().ByName("AddDeck")
	wordVaultServiceGetDecksMethodDescriptor                 = wordVaultServiceServiceDescriptor.Methods().ByName("GetDecks")
	wordVaultServiceEditDeckMethodDescriptor                 = wordVaultServiceServiceDescriptor.Methods().ByName("EditDeck")
	wordVaultServiceDeleteDeckMethodDescriptor               = wordVaultServiceServiceDescriptor.Methods().ByName("DeleteDeck")
)

// WordVaultServiceClient is a client for the wordvault.WordVaultService service.
type WordVaultServiceClient interface {
	GetCardCount(context.Context, *connect.Request[wordvault.GetCardCountRequest]) (*connect.Response[wordvault.CardCountResponse], error)
	GetCardCountByDeck(context.Context, *connect.Request[wordvault.GetCardCountByDeckRequest]) (*connect.Response[wordvault.GetCardCountByDeckResponse], error)
	GetCardInformation(context.Context, *connect.Request[wordvault.GetCardInfoRequest]) (*connect.Response[wordvault.Cards], error)
	GetNextScheduled(context.Context, *connect.Request[wordvault.GetNextScheduledRequest]) (*connect.Response[wordvault.Cards], error)
	GetSingleNextScheduled(context.Context, *connect.Request[wordvault.GetSingleNextScheduledRequest]) (*connect.Response[wordvault.GetSingleNextScheduledResponse], error)
	NextScheduledCount(context.Context, *connect.Request[wordvault.NextScheduledCountRequest]) (*connect.Response[wordvault.NextScheduledBreakdown], error)
	NextScheduledCountByDeck(context.Context, *connect.Request[wordvault.NextScheduledCountByDeckRequest]) (*connect.Response[wordvault.NextScheduledCountByDeckResponse], error)
	ScoreCard(context.Context, *connect.Request[wordvault.ScoreCardRequest]) (*connect.Response[wordvault.ScoreCardResponse], error)
	EditLastScore(context.Context, *connect.Request[wordvault.EditLastScoreRequest]) (*connect.Response[wordvault.ScoreCardResponse], error)
	AddCards(context.Context, *connect.Request[wordvault.AddCardsRequest]) (*connect.Response[wordvault.AddCardsResponse], error)
	MoveCards(context.Context, *connect.Request[wordvault.MoveCardsRequest]) (*connect.Response[wordvault.MoveCardsResponse], error)
	Postpone(context.Context, *connect.Request[wordvault.PostponeRequest]) (*connect.Response[wordvault.PostponeResponse], error)
	Delete(context.Context, *connect.Request[wordvault.DeleteRequest]) (*connect.Response[wordvault.DeleteResponse], error)
	DeleteFromDeck(context.Context, *connect.Request[wordvault.DeleteFromDeckRequest]) (*connect.Response[wordvault.DeleteResponse], error)
	GetDailyProgress(context.Context, *connect.Request[wordvault.GetDailyProgressRequest]) (*connect.Response[wordvault.GetDailyProgressResponse], error)
	GetDailyProgressByDeck(context.Context, *connect.Request[wordvault.GetDailyProgressByDeckRequest]) (*connect.Response[wordvault.GetDailyProgressByDeckResponse], error)
	GetDailyLeaderboard(context.Context, *connect.Request[wordvault.GetDailyLeaderboardRequest]) (*connect.Response[wordvault.GetDailyLeaderboardResponse], error)
	AddDeck(context.Context, *connect.Request[wordvault.AddDeckRequest]) (*connect.Response[wordvault.AddDeckResponse], error)
	GetDecks(context.Context, *connect.Request[wordvault.GetDecksRequest]) (*connect.Response[wordvault.GetDecksResponse], error)
	EditDeck(context.Context, *connect.Request[wordvault.EditDeckRequest]) (*connect.Response[wordvault.EditDeckResponse], error)
	DeleteDeck(context.Context, *connect.Request[wordvault.DeleteDeckRequest]) (*connect.Response[wordvault.DeleteDeckResponse], error)
}

// NewWordVaultServiceClient constructs a client for the wordvault.WordVaultService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWordVaultServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WordVaultServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &wordVaultServiceClient{
		getCardCount: connect.NewClient[wordvault.GetCardCountRequest, wordvault.CardCountResponse](
			httpClient,
			baseURL+WordVaultServiceGetCardCountProcedure,
			connect.WithSchema(wordVaultServiceGetCardCountMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getCardCountByDeck: connect.NewClient[wordvault.GetCardCountByDeckRequest, wordvault.GetCardCountByDeckResponse](
			httpClient,
			baseURL+WordVaultServiceGetCardCountByDeckProcedure,
			connect.WithSchema(wordVaultServiceGetCardCountByDeckMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getCardInformation: connect.NewClient[wordvault.GetCardInfoRequest, wordvault.Cards](
			httpClient,
			baseURL+WordVaultServiceGetCardInformationProcedure,
			connect.WithSchema(wordVaultServiceGetCardInformationMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getNextScheduled: connect.NewClient[wordvault.GetNextScheduledRequest, wordvault.Cards](
			httpClient,
			baseURL+WordVaultServiceGetNextScheduledProcedure,
			connect.WithSchema(wordVaultServiceGetNextScheduledMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getSingleNextScheduled: connect.NewClient[wordvault.GetSingleNextScheduledRequest, wordvault.GetSingleNextScheduledResponse](
			httpClient,
			baseURL+WordVaultServiceGetSingleNextScheduledProcedure,
			connect.WithSchema(wordVaultServiceGetSingleNextScheduledMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		nextScheduledCount: connect.NewClient[wordvault.NextScheduledCountRequest, wordvault.NextScheduledBreakdown](
			httpClient,
			baseURL+WordVaultServiceNextScheduledCountProcedure,
			connect.WithSchema(wordVaultServiceNextScheduledCountMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		nextScheduledCountByDeck: connect.NewClient[wordvault.NextScheduledCountByDeckRequest, wordvault.NextScheduledCountByDeckResponse](
			httpClient,
			baseURL+WordVaultServiceNextScheduledCountByDeckProcedure,
			connect.WithSchema(wordVaultServiceNextScheduledCountByDeckMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		scoreCard: connect.NewClient[wordvault.ScoreCardRequest, wordvault.ScoreCardResponse](
			httpClient,
			baseURL+WordVaultServiceScoreCardProcedure,
			connect.WithSchema(wordVaultServiceScoreCardMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		editLastScore: connect.NewClient[wordvault.EditLastScoreRequest, wordvault.ScoreCardResponse](
			httpClient,
			baseURL+WordVaultServiceEditLastScoreProcedure,
			connect.WithSchema(wordVaultServiceEditLastScoreMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		addCards: connect.NewClient[wordvault.AddCardsRequest, wordvault.AddCardsResponse](
			httpClient,
			baseURL+WordVaultServiceAddCardsProcedure,
			connect.WithSchema(wordVaultServiceAddCardsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		moveCards: connect.NewClient[wordvault.MoveCardsRequest, wordvault.MoveCardsResponse](
			httpClient,
			baseURL+WordVaultServiceMoveCardsProcedure,
			connect.WithSchema(wordVaultServiceMoveCardsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		postpone: connect.NewClient[wordvault.PostponeRequest, wordvault.PostponeResponse](
			httpClient,
			baseURL+WordVaultServicePostponeProcedure,
			connect.WithSchema(wordVaultServicePostponeMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[wordvault.DeleteRequest, wordvault.DeleteResponse](
			httpClient,
			baseURL+WordVaultServiceDeleteProcedure,
			connect.WithSchema(wordVaultServiceDeleteMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteFromDeck: connect.NewClient[wordvault.DeleteFromDeckRequest, wordvault.DeleteResponse](
			httpClient,
			baseURL+WordVaultServiceDeleteFromDeckProcedure,
			connect.WithSchema(wordVaultServiceDeleteFromDeckMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getDailyProgress: connect.NewClient[wordvault.GetDailyProgressRequest, wordvault.GetDailyProgressResponse](
			httpClient,
			baseURL+WordVaultServiceGetDailyProgressProcedure,
			connect.WithSchema(wordVaultServiceGetDailyProgressMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getDailyProgressByDeck: connect.NewClient[wordvault.GetDailyProgressByDeckRequest, wordvault.GetDailyProgressByDeckResponse](
			httpClient,
			baseURL+WordVaultServiceGetDailyProgressByDeckProcedure,
			connect.WithSchema(wordVaultServiceGetDailyProgressByDeckMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getDailyLeaderboard: connect.NewClient[wordvault.GetDailyLeaderboardRequest, wordvault.GetDailyLeaderboardResponse](
			httpClient,
			baseURL+WordVaultServiceGetDailyLeaderboardProcedure,
			connect.WithSchema(wordVaultServiceGetDailyLeaderboardMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		addDeck: connect.NewClient[wordvault.AddDeckRequest, wordvault.AddDeckResponse](
			httpClient,
			baseURL+WordVaultServiceAddDeckProcedure,
			connect.WithSchema(wordVaultServiceAddDeckMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getDecks: connect.NewClient[wordvault.GetDecksRequest, wordvault.GetDecksResponse](
			httpClient,
			baseURL+WordVaultServiceGetDecksProcedure,
			connect.WithSchema(wordVaultServiceGetDecksMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		editDeck: connect.NewClient[wordvault.EditDeckRequest, wordvault.EditDeckResponse](
			httpClient,
			baseURL+WordVaultServiceEditDeckProcedure,
			connect.WithSchema(wordVaultServiceEditDeckMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteDeck: connect.NewClient[wordvault.DeleteDeckRequest, wordvault.DeleteDeckResponse](
			httpClient,
			baseURL+WordVaultServiceDeleteDeckProcedure,
			connect.WithSchema(wordVaultServiceDeleteDeckMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// wordVaultServiceClient implements WordVaultServiceClient.
type wordVaultServiceClient struct {
	getCardCount             *connect.Client[wordvault.GetCardCountRequest, wordvault.CardCountResponse]
	getCardCountByDeck       *connect.Client[wordvault.GetCardCountByDeckRequest, wordvault.GetCardCountByDeckResponse]
	getCardInformation       *connect.Client[wordvault.GetCardInfoRequest, wordvault.Cards]
	getNextScheduled         *connect.Client[wordvault.GetNextScheduledRequest, wordvault.Cards]
	getSingleNextScheduled   *connect.Client[wordvault.GetSingleNextScheduledRequest, wordvault.GetSingleNextScheduledResponse]
	nextScheduledCount       *connect.Client[wordvault.NextScheduledCountRequest, wordvault.NextScheduledBreakdown]
	nextScheduledCountByDeck *connect.Client[wordvault.NextScheduledCountByDeckRequest, wordvault.NextScheduledCountByDeckResponse]
	scoreCard                *connect.Client[wordvault.ScoreCardRequest, wordvault.ScoreCardResponse]
	editLastScore            *connect.Client[wordvault.EditLastScoreRequest, wordvault.ScoreCardResponse]
	addCards                 *connect.Client[wordvault.AddCardsRequest, wordvault.AddCardsResponse]
	moveCards                *connect.Client[wordvault.MoveCardsRequest, wordvault.MoveCardsResponse]
	postpone                 *connect.Client[wordvault.PostponeRequest, wordvault.PostponeResponse]
	delete                   *connect.Client[wordvault.DeleteRequest, wordvault.DeleteResponse]
	deleteFromDeck           *connect.Client[wordvault.DeleteFromDeckRequest, wordvault.DeleteResponse]
	getDailyProgress         *connect.Client[wordvault.GetDailyProgressRequest, wordvault.GetDailyProgressResponse]
	getDailyProgressByDeck   *connect.Client[wordvault.GetDailyProgressByDeckRequest, wordvault.GetDailyProgressByDeckResponse]
	getDailyLeaderboard      *connect.Client[wordvault.GetDailyLeaderboardRequest, wordvault.GetDailyLeaderboardResponse]
	addDeck                  *connect.Client[wordvault.AddDeckRequest, wordvault.AddDeckResponse]
	getDecks                 *connect.Client[wordvault.GetDecksRequest, wordvault.GetDecksResponse]
	editDeck                 *connect.Client[wordvault.EditDeckRequest, wordvault.EditDeckResponse]
	deleteDeck               *connect.Client[wordvault.DeleteDeckRequest, wordvault.DeleteDeckResponse]
}

// GetCardCount calls wordvault.WordVaultService.GetCardCount.
func (c *wordVaultServiceClient) GetCardCount(ctx context.Context, req *connect.Request[wordvault.GetCardCountRequest]) (*connect.Response[wordvault.CardCountResponse], error) {
	return c.getCardCount.CallUnary(ctx, req)
}

// GetCardCountByDeck calls wordvault.WordVaultService.GetCardCountByDeck.
func (c *wordVaultServiceClient) GetCardCountByDeck(ctx context.Context, req *connect.Request[wordvault.GetCardCountByDeckRequest]) (*connect.Response[wordvault.GetCardCountByDeckResponse], error) {
	return c.getCardCountByDeck.CallUnary(ctx, req)
}

// GetCardInformation calls wordvault.WordVaultService.GetCardInformation.
func (c *wordVaultServiceClient) GetCardInformation(ctx context.Context, req *connect.Request[wordvault.GetCardInfoRequest]) (*connect.Response[wordvault.Cards], error) {
	return c.getCardInformation.CallUnary(ctx, req)
}

// GetNextScheduled calls wordvault.WordVaultService.GetNextScheduled.
func (c *wordVaultServiceClient) GetNextScheduled(ctx context.Context, req *connect.Request[wordvault.GetNextScheduledRequest]) (*connect.Response[wordvault.Cards], error) {
	return c.getNextScheduled.CallUnary(ctx, req)
}

// GetSingleNextScheduled calls wordvault.WordVaultService.GetSingleNextScheduled.
func (c *wordVaultServiceClient) GetSingleNextScheduled(ctx context.Context, req *connect.Request[wordvault.GetSingleNextScheduledRequest]) (*connect.Response[wordvault.GetSingleNextScheduledResponse], error) {
	return c.getSingleNextScheduled.CallUnary(ctx, req)
}

// NextScheduledCount calls wordvault.WordVaultService.NextScheduledCount.
func (c *wordVaultServiceClient) NextScheduledCount(ctx context.Context, req *connect.Request[wordvault.NextScheduledCountRequest]) (*connect.Response[wordvault.NextScheduledBreakdown], error) {
	return c.nextScheduledCount.CallUnary(ctx, req)
}

// NextScheduledCountByDeck calls wordvault.WordVaultService.NextScheduledCountByDeck.
func (c *wordVaultServiceClient) NextScheduledCountByDeck(ctx context.Context, req *connect.Request[wordvault.NextScheduledCountByDeckRequest]) (*connect.Response[wordvault.NextScheduledCountByDeckResponse], error) {
	return c.nextScheduledCountByDeck.CallUnary(ctx, req)
}

// ScoreCard calls wordvault.WordVaultService.ScoreCard.
func (c *wordVaultServiceClient) ScoreCard(ctx context.Context, req *connect.Request[wordvault.ScoreCardRequest]) (*connect.Response[wordvault.ScoreCardResponse], error) {
	return c.scoreCard.CallUnary(ctx, req)
}

// EditLastScore calls wordvault.WordVaultService.EditLastScore.
func (c *wordVaultServiceClient) EditLastScore(ctx context.Context, req *connect.Request[wordvault.EditLastScoreRequest]) (*connect.Response[wordvault.ScoreCardResponse], error) {
	return c.editLastScore.CallUnary(ctx, req)
}

// AddCards calls wordvault.WordVaultService.AddCards.
func (c *wordVaultServiceClient) AddCards(ctx context.Context, req *connect.Request[wordvault.AddCardsRequest]) (*connect.Response[wordvault.AddCardsResponse], error) {
	return c.addCards.CallUnary(ctx, req)
}

// MoveCards calls wordvault.WordVaultService.MoveCards.
func (c *wordVaultServiceClient) MoveCards(ctx context.Context, req *connect.Request[wordvault.MoveCardsRequest]) (*connect.Response[wordvault.MoveCardsResponse], error) {
	return c.moveCards.CallUnary(ctx, req)
}

// Postpone calls wordvault.WordVaultService.Postpone.
func (c *wordVaultServiceClient) Postpone(ctx context.Context, req *connect.Request[wordvault.PostponeRequest]) (*connect.Response[wordvault.PostponeResponse], error) {
	return c.postpone.CallUnary(ctx, req)
}

// Delete calls wordvault.WordVaultService.Delete.
func (c *wordVaultServiceClient) Delete(ctx context.Context, req *connect.Request[wordvault.DeleteRequest]) (*connect.Response[wordvault.DeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// DeleteFromDeck calls wordvault.WordVaultService.DeleteFromDeck.
func (c *wordVaultServiceClient) DeleteFromDeck(ctx context.Context, req *connect.Request[wordvault.DeleteFromDeckRequest]) (*connect.Response[wordvault.DeleteResponse], error) {
	return c.deleteFromDeck.CallUnary(ctx, req)
}

// GetDailyProgress calls wordvault.WordVaultService.GetDailyProgress.
func (c *wordVaultServiceClient) GetDailyProgress(ctx context.Context, req *connect.Request[wordvault.GetDailyProgressRequest]) (*connect.Response[wordvault.GetDailyProgressResponse], error) {
	return c.getDailyProgress.CallUnary(ctx, req)
}

// GetDailyProgressByDeck calls wordvault.WordVaultService.GetDailyProgressByDeck.
func (c *wordVaultServiceClient) GetDailyProgressByDeck(ctx context.Context, req *connect.Request[wordvault.GetDailyProgressByDeckRequest]) (*connect.Response[wordvault.GetDailyProgressByDeckResponse], error) {
	return c.getDailyProgressByDeck.CallUnary(ctx, req)
}

// GetDailyLeaderboard calls wordvault.WordVaultService.GetDailyLeaderboard.
func (c *wordVaultServiceClient) GetDailyLeaderboard(ctx context.Context, req *connect.Request[wordvault.GetDailyLeaderboardRequest]) (*connect.Response[wordvault.GetDailyLeaderboardResponse], error) {
	return c.getDailyLeaderboard.CallUnary(ctx, req)
}

// AddDeck calls wordvault.WordVaultService.AddDeck.
func (c *wordVaultServiceClient) AddDeck(ctx context.Context, req *connect.Request[wordvault.AddDeckRequest]) (*connect.Response[wordvault.AddDeckResponse], error) {
	return c.addDeck.CallUnary(ctx, req)
}

// GetDecks calls wordvault.WordVaultService.GetDecks.
func (c *wordVaultServiceClient) GetDecks(ctx context.Context, req *connect.Request[wordvault.GetDecksRequest]) (*connect.Response[wordvault.GetDecksResponse], error) {
	return c.getDecks.CallUnary(ctx, req)
}

// EditDeck calls wordvault.WordVaultService.EditDeck.
func (c *wordVaultServiceClient) EditDeck(ctx context.Context, req *connect.Request[wordvault.EditDeckRequest]) (*connect.Response[wordvault.EditDeckResponse], error) {
	return c.editDeck.CallUnary(ctx, req)
}

// DeleteDeck calls wordvault.WordVaultService.DeleteDeck.
func (c *wordVaultServiceClient) DeleteDeck(ctx context.Context, req *connect.Request[wordvault.DeleteDeckRequest]) (*connect.Response[wordvault.DeleteDeckResponse], error) {
	return c.deleteDeck.CallUnary(ctx, req)
}

// WordVaultServiceHandler is an implementation of the wordvault.WordVaultService service.
type WordVaultServiceHandler interface {
	GetCardCount(context.Context, *connect.Request[wordvault.GetCardCountRequest]) (*connect.Response[wordvault.CardCountResponse], error)
	GetCardCountByDeck(context.Context, *connect.Request[wordvault.GetCardCountByDeckRequest]) (*connect.Response[wordvault.GetCardCountByDeckResponse], error)
	GetCardInformation(context.Context, *connect.Request[wordvault.GetCardInfoRequest]) (*connect.Response[wordvault.Cards], error)
	GetNextScheduled(context.Context, *connect.Request[wordvault.GetNextScheduledRequest]) (*connect.Response[wordvault.Cards], error)
	GetSingleNextScheduled(context.Context, *connect.Request[wordvault.GetSingleNextScheduledRequest]) (*connect.Response[wordvault.GetSingleNextScheduledResponse], error)
	NextScheduledCount(context.Context, *connect.Request[wordvault.NextScheduledCountRequest]) (*connect.Response[wordvault.NextScheduledBreakdown], error)
	NextScheduledCountByDeck(context.Context, *connect.Request[wordvault.NextScheduledCountByDeckRequest]) (*connect.Response[wordvault.NextScheduledCountByDeckResponse], error)
	ScoreCard(context.Context, *connect.Request[wordvault.ScoreCardRequest]) (*connect.Response[wordvault.ScoreCardResponse], error)
	EditLastScore(context.Context, *connect.Request[wordvault.EditLastScoreRequest]) (*connect.Response[wordvault.ScoreCardResponse], error)
	AddCards(context.Context, *connect.Request[wordvault.AddCardsRequest]) (*connect.Response[wordvault.AddCardsResponse], error)
	MoveCards(context.Context, *connect.Request[wordvault.MoveCardsRequest]) (*connect.Response[wordvault.MoveCardsResponse], error)
	Postpone(context.Context, *connect.Request[wordvault.PostponeRequest]) (*connect.Response[wordvault.PostponeResponse], error)
	Delete(context.Context, *connect.Request[wordvault.DeleteRequest]) (*connect.Response[wordvault.DeleteResponse], error)
	DeleteFromDeck(context.Context, *connect.Request[wordvault.DeleteFromDeckRequest]) (*connect.Response[wordvault.DeleteResponse], error)
	GetDailyProgress(context.Context, *connect.Request[wordvault.GetDailyProgressRequest]) (*connect.Response[wordvault.GetDailyProgressResponse], error)
	GetDailyProgressByDeck(context.Context, *connect.Request[wordvault.GetDailyProgressByDeckRequest]) (*connect.Response[wordvault.GetDailyProgressByDeckResponse], error)
	GetDailyLeaderboard(context.Context, *connect.Request[wordvault.GetDailyLeaderboardRequest]) (*connect.Response[wordvault.GetDailyLeaderboardResponse], error)
	AddDeck(context.Context, *connect.Request[wordvault.AddDeckRequest]) (*connect.Response[wordvault.AddDeckResponse], error)
	GetDecks(context.Context, *connect.Request[wordvault.GetDecksRequest]) (*connect.Response[wordvault.GetDecksResponse], error)
	EditDeck(context.Context, *connect.Request[wordvault.EditDeckRequest]) (*connect.Response[wordvault.EditDeckResponse], error)
	DeleteDeck(context.Context, *connect.Request[wordvault.DeleteDeckRequest]) (*connect.Response[wordvault.DeleteDeckResponse], error)
}

// NewWordVaultServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWordVaultServiceHandler(svc WordVaultServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	wordVaultServiceGetCardCountHandler := connect.NewUnaryHandler(
		WordVaultServiceGetCardCountProcedure,
		svc.GetCardCount,
		connect.WithSchema(wordVaultServiceGetCardCountMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceGetCardCountByDeckHandler := connect.NewUnaryHandler(
		WordVaultServiceGetCardCountByDeckProcedure,
		svc.GetCardCountByDeck,
		connect.WithSchema(wordVaultServiceGetCardCountByDeckMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceGetCardInformationHandler := connect.NewUnaryHandler(
		WordVaultServiceGetCardInformationProcedure,
		svc.GetCardInformation,
		connect.WithSchema(wordVaultServiceGetCardInformationMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceGetNextScheduledHandler := connect.NewUnaryHandler(
		WordVaultServiceGetNextScheduledProcedure,
		svc.GetNextScheduled,
		connect.WithSchema(wordVaultServiceGetNextScheduledMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceGetSingleNextScheduledHandler := connect.NewUnaryHandler(
		WordVaultServiceGetSingleNextScheduledProcedure,
		svc.GetSingleNextScheduled,
		connect.WithSchema(wordVaultServiceGetSingleNextScheduledMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceNextScheduledCountHandler := connect.NewUnaryHandler(
		WordVaultServiceNextScheduledCountProcedure,
		svc.NextScheduledCount,
		connect.WithSchema(wordVaultServiceNextScheduledCountMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceNextScheduledCountByDeckHandler := connect.NewUnaryHandler(
		WordVaultServiceNextScheduledCountByDeckProcedure,
		svc.NextScheduledCountByDeck,
		connect.WithSchema(wordVaultServiceNextScheduledCountByDeckMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceScoreCardHandler := connect.NewUnaryHandler(
		WordVaultServiceScoreCardProcedure,
		svc.ScoreCard,
		connect.WithSchema(wordVaultServiceScoreCardMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceEditLastScoreHandler := connect.NewUnaryHandler(
		WordVaultServiceEditLastScoreProcedure,
		svc.EditLastScore,
		connect.WithSchema(wordVaultServiceEditLastScoreMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceAddCardsHandler := connect.NewUnaryHandler(
		WordVaultServiceAddCardsProcedure,
		svc.AddCards,
		connect.WithSchema(wordVaultServiceAddCardsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceMoveCardsHandler := connect.NewUnaryHandler(
		WordVaultServiceMoveCardsProcedure,
		svc.MoveCards,
		connect.WithSchema(wordVaultServiceMoveCardsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServicePostponeHandler := connect.NewUnaryHandler(
		WordVaultServicePostponeProcedure,
		svc.Postpone,
		connect.WithSchema(wordVaultServicePostponeMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceDeleteHandler := connect.NewUnaryHandler(
		WordVaultServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(wordVaultServiceDeleteMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceDeleteFromDeckHandler := connect.NewUnaryHandler(
		WordVaultServiceDeleteFromDeckProcedure,
		svc.DeleteFromDeck,
		connect.WithSchema(wordVaultServiceDeleteFromDeckMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceGetDailyProgressHandler := connect.NewUnaryHandler(
		WordVaultServiceGetDailyProgressProcedure,
		svc.GetDailyProgress,
		connect.WithSchema(wordVaultServiceGetDailyProgressMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceGetDailyProgressByDeckHandler := connect.NewUnaryHandler(
		WordVaultServiceGetDailyProgressByDeckProcedure,
		svc.GetDailyProgressByDeck,
		connect.WithSchema(wordVaultServiceGetDailyProgressByDeckMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceGetDailyLeaderboardHandler := connect.NewUnaryHandler(
		WordVaultServiceGetDailyLeaderboardProcedure,
		svc.GetDailyLeaderboard,
		connect.WithSchema(wordVaultServiceGetDailyLeaderboardMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceAddDeckHandler := connect.NewUnaryHandler(
		WordVaultServiceAddDeckProcedure,
		svc.AddDeck,
		connect.WithSchema(wordVaultServiceAddDeckMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceGetDecksHandler := connect.NewUnaryHandler(
		WordVaultServiceGetDecksProcedure,
		svc.GetDecks,
		connect.WithSchema(wordVaultServiceGetDecksMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceEditDeckHandler := connect.NewUnaryHandler(
		WordVaultServiceEditDeckProcedure,
		svc.EditDeck,
		connect.WithSchema(wordVaultServiceEditDeckMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	wordVaultServiceDeleteDeckHandler := connect.NewUnaryHandler(
		WordVaultServiceDeleteDeckProcedure,
		svc.DeleteDeck,
		connect.WithSchema(wordVaultServiceDeleteDeckMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/wordvault.WordVaultService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WordVaultServiceGetCardCountProcedure:
			wordVaultServiceGetCardCountHandler.ServeHTTP(w, r)
		case WordVaultServiceGetCardCountByDeckProcedure:
			wordVaultServiceGetCardCountByDeckHandler.ServeHTTP(w, r)
		case WordVaultServiceGetCardInformationProcedure:
			wordVaultServiceGetCardInformationHandler.ServeHTTP(w, r)
		case WordVaultServiceGetNextScheduledProcedure:
			wordVaultServiceGetNextScheduledHandler.ServeHTTP(w, r)
		case WordVaultServiceGetSingleNextScheduledProcedure:
			wordVaultServiceGetSingleNextScheduledHandler.ServeHTTP(w, r)
		case WordVaultServiceNextScheduledCountProcedure:
			wordVaultServiceNextScheduledCountHandler.ServeHTTP(w, r)
		case WordVaultServiceNextScheduledCountByDeckProcedure:
			wordVaultServiceNextScheduledCountByDeckHandler.ServeHTTP(w, r)
		case WordVaultServiceScoreCardProcedure:
			wordVaultServiceScoreCardHandler.ServeHTTP(w, r)
		case WordVaultServiceEditLastScoreProcedure:
			wordVaultServiceEditLastScoreHandler.ServeHTTP(w, r)
		case WordVaultServiceAddCardsProcedure:
			wordVaultServiceAddCardsHandler.ServeHTTP(w, r)
		case WordVaultServiceMoveCardsProcedure:
			wordVaultServiceMoveCardsHandler.ServeHTTP(w, r)
		case WordVaultServicePostponeProcedure:
			wordVaultServicePostponeHandler.ServeHTTP(w, r)
		case WordVaultServiceDeleteProcedure:
			wordVaultServiceDeleteHandler.ServeHTTP(w, r)
		case WordVaultServiceDeleteFromDeckProcedure:
			wordVaultServiceDeleteFromDeckHandler.ServeHTTP(w, r)
		case WordVaultServiceGetDailyProgressProcedure:
			wordVaultServiceGetDailyProgressHandler.ServeHTTP(w, r)
		case WordVaultServiceGetDailyProgressByDeckProcedure:
			wordVaultServiceGetDailyProgressByDeckHandler.ServeHTTP(w, r)
		case WordVaultServiceGetDailyLeaderboardProcedure:
			wordVaultServiceGetDailyLeaderboardHandler.ServeHTTP(w, r)
		case WordVaultServiceAddDeckProcedure:
			wordVaultServiceAddDeckHandler.ServeHTTP(w, r)
		case WordVaultServiceGetDecksProcedure:
			wordVaultServiceGetDecksHandler.ServeHTTP(w, r)
		case WordVaultServiceEditDeckProcedure:
			wordVaultServiceEditDeckHandler.ServeHTTP(w, r)
		case WordVaultServiceDeleteDeckProcedure:
			wordVaultServiceDeleteDeckHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWordVaultServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWordVaultServiceHandler struct{}

func (UnimplementedWordVaultServiceHandler) GetCardCount(context.Context, *connect.Request[wordvault.GetCardCountRequest]) (*connect.Response[wordvault.CardCountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.GetCardCount is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) GetCardCountByDeck(context.Context, *connect.Request[wordvault.GetCardCountByDeckRequest]) (*connect.Response[wordvault.GetCardCountByDeckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.GetCardCountByDeck is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) GetCardInformation(context.Context, *connect.Request[wordvault.GetCardInfoRequest]) (*connect.Response[wordvault.Cards], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.GetCardInformation is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) GetNextScheduled(context.Context, *connect.Request[wordvault.GetNextScheduledRequest]) (*connect.Response[wordvault.Cards], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.GetNextScheduled is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) GetSingleNextScheduled(context.Context, *connect.Request[wordvault.GetSingleNextScheduledRequest]) (*connect.Response[wordvault.GetSingleNextScheduledResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.GetSingleNextScheduled is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) NextScheduledCount(context.Context, *connect.Request[wordvault.NextScheduledCountRequest]) (*connect.Response[wordvault.NextScheduledBreakdown], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.NextScheduledCount is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) NextScheduledCountByDeck(context.Context, *connect.Request[wordvault.NextScheduledCountByDeckRequest]) (*connect.Response[wordvault.NextScheduledCountByDeckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.NextScheduledCountByDeck is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) ScoreCard(context.Context, *connect.Request[wordvault.ScoreCardRequest]) (*connect.Response[wordvault.ScoreCardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.ScoreCard is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) EditLastScore(context.Context, *connect.Request[wordvault.EditLastScoreRequest]) (*connect.Response[wordvault.ScoreCardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.EditLastScore is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) AddCards(context.Context, *connect.Request[wordvault.AddCardsRequest]) (*connect.Response[wordvault.AddCardsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.AddCards is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) MoveCards(context.Context, *connect.Request[wordvault.MoveCardsRequest]) (*connect.Response[wordvault.MoveCardsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.MoveCards is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) Postpone(context.Context, *connect.Request[wordvault.PostponeRequest]) (*connect.Response[wordvault.PostponeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.Postpone is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) Delete(context.Context, *connect.Request[wordvault.DeleteRequest]) (*connect.Response[wordvault.DeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.Delete is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) DeleteFromDeck(context.Context, *connect.Request[wordvault.DeleteFromDeckRequest]) (*connect.Response[wordvault.DeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.DeleteFromDeck is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) GetDailyProgress(context.Context, *connect.Request[wordvault.GetDailyProgressRequest]) (*connect.Response[wordvault.GetDailyProgressResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.GetDailyProgress is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) GetDailyProgressByDeck(context.Context, *connect.Request[wordvault.GetDailyProgressByDeckRequest]) (*connect.Response[wordvault.GetDailyProgressByDeckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.GetDailyProgressByDeck is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) GetDailyLeaderboard(context.Context, *connect.Request[wordvault.GetDailyLeaderboardRequest]) (*connect.Response[wordvault.GetDailyLeaderboardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.GetDailyLeaderboard is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) AddDeck(context.Context, *connect.Request[wordvault.AddDeckRequest]) (*connect.Response[wordvault.AddDeckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.AddDeck is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) GetDecks(context.Context, *connect.Request[wordvault.GetDecksRequest]) (*connect.Response[wordvault.GetDecksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.GetDecks is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) EditDeck(context.Context, *connect.Request[wordvault.EditDeckRequest]) (*connect.Response[wordvault.EditDeckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.EditDeck is not implemented"))
}

func (UnimplementedWordVaultServiceHandler) DeleteDeck(context.Context, *connect.Request[wordvault.DeleteDeckRequest]) (*connect.Response[wordvault.DeleteDeckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wordvault.WordVaultService.DeleteDeck is not implemented"))
}
