// Code generated by protoc-gen-twirp v7.1.0, DO NOT EDIT.
// source: rpc/wordsearcher/searcher.proto

/*
Package wordsearcher is a generated twirp stub package.
This code was generated with github.com/twitchtv/twirp/protoc-gen-twirp v7.1.0.

It is generated from these files:
	rpc/wordsearcher/searcher.proto
*/
package wordsearcher

import bytes "bytes"
import strings "strings"
import context "context"
import fmt "fmt"
import ioutil "io/ioutil"
import http "net/http"
import strconv "strconv"

import jsonpb "github.com/golang/protobuf/jsonpb"
import proto "github.com/golang/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Imports only used by utility functions:
import io "io"
import json "encoding/json"
import path "path"
import url "net/url"

// This is a compile-time assertion to ensure that this generated file
// is compatible with the twirp package used in your project.
// A compilation error at this line likely means your copy of the
// twirp package needs to be updated.
const _ = twirp.TwirpPackageIsVersion7

// ==========================
// QuestionSearcher Interface
// ==========================

// QuestionSearcher service searches for questions (duh!)
type QuestionSearcher interface {
	// Search takes in a search request and returns a search response.
	// This response can be expanded or not, depending on the `expand` field
	// in SearchRequest.
	Search(context.Context, *SearchRequest) (*SearchResponse, error)

	// Expand takes in an unexpanded search response and returns a
	// search response (fully expanded). See expandedRepr above in
	// the Alphagram field.
	Expand(context.Context, *SearchResponse) (*SearchResponse, error)
}

// ================================
// QuestionSearcher Protobuf Client
// ================================

type questionSearcherProtobufClient struct {
	client      HTTPClient
	urls        [2]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewQuestionSearcherProtobufClient creates a Protobuf client that implements the QuestionSearcher interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewQuestionSearcherProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) QuestionSearcher {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(clientOpts.PathPrefix(), "wordsearcher", "QuestionSearcher")
	urls := [2]string{
		serviceURL + "Search",
		serviceURL + "Expand",
	}

	return &questionSearcherProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *questionSearcherProtobufClient) Search(ctx context.Context, in *SearchRequest) (*SearchResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "wordsearcher")
	ctx = ctxsetters.WithServiceName(ctx, "QuestionSearcher")
	ctx = ctxsetters.WithMethodName(ctx, "Search")
	caller := c.callSearch
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SearchRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SearchRequest) when calling interceptor")
					}
					return c.callSearch(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *questionSearcherProtobufClient) callSearch(ctx context.Context, in *SearchRequest) (*SearchResponse, error) {
	out := new(SearchResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *questionSearcherProtobufClient) Expand(ctx context.Context, in *SearchResponse) (*SearchResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "wordsearcher")
	ctx = ctxsetters.WithServiceName(ctx, "QuestionSearcher")
	ctx = ctxsetters.WithMethodName(ctx, "Expand")
	caller := c.callExpand
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *SearchResponse) (*SearchResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SearchResponse)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SearchResponse) when calling interceptor")
					}
					return c.callExpand(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *questionSearcherProtobufClient) callExpand(ctx context.Context, in *SearchResponse) (*SearchResponse, error) {
	out := new(SearchResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ============================
// QuestionSearcher JSON Client
// ============================

type questionSearcherJSONClient struct {
	client      HTTPClient
	urls        [2]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewQuestionSearcherJSONClient creates a JSON client that implements the QuestionSearcher interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewQuestionSearcherJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) QuestionSearcher {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(clientOpts.PathPrefix(), "wordsearcher", "QuestionSearcher")
	urls := [2]string{
		serviceURL + "Search",
		serviceURL + "Expand",
	}

	return &questionSearcherJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *questionSearcherJSONClient) Search(ctx context.Context, in *SearchRequest) (*SearchResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "wordsearcher")
	ctx = ctxsetters.WithServiceName(ctx, "QuestionSearcher")
	ctx = ctxsetters.WithMethodName(ctx, "Search")
	caller := c.callSearch
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SearchRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SearchRequest) when calling interceptor")
					}
					return c.callSearch(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *questionSearcherJSONClient) callSearch(ctx context.Context, in *SearchRequest) (*SearchResponse, error) {
	out := new(SearchResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *questionSearcherJSONClient) Expand(ctx context.Context, in *SearchResponse) (*SearchResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "wordsearcher")
	ctx = ctxsetters.WithServiceName(ctx, "QuestionSearcher")
	ctx = ctxsetters.WithMethodName(ctx, "Expand")
	caller := c.callExpand
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *SearchResponse) (*SearchResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SearchResponse)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SearchResponse) when calling interceptor")
					}
					return c.callExpand(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *questionSearcherJSONClient) callExpand(ctx context.Context, in *SearchResponse) (*SearchResponse, error) {
	out := new(SearchResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ===============================
// QuestionSearcher Server Handler
// ===============================

type questionSearcherServer struct {
	QuestionSearcher
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
}

// NewQuestionSearcherServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewQuestionSearcherServer(svc QuestionSearcher, opts ...interface{}) TwirpServer {
	serverOpts := twirp.ServerOptions{}
	for _, opt := range opts {
		switch o := opt.(type) {
		case twirp.ServerOption:
			o(&serverOpts)
		case *twirp.ServerHooks: // backwards compatibility, allow to specify hooks as an argument
			twirp.WithServerHooks(o)(&serverOpts)
		case nil: // backwards compatibility, allow nil value for the argument
			continue
		default:
			panic(fmt.Sprintf("Invalid option type %T on NewQuestionSearcherServer", o))
		}
	}

	return &questionSearcherServer{
		QuestionSearcher: svc,
		pathPrefix:       serverOpts.PathPrefix(),
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		hooks:            serverOpts.Hooks,
		jsonSkipDefaults: serverOpts.JSONSkipDefaults,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *questionSearcherServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// QuestionSearcherPathPrefix is a convenience constant that could used to identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// that add a "/twirp" prefix by default, and use CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const QuestionSearcherPathPrefix = "/twirp/wordsearcher.QuestionSearcher/"

func (s *questionSearcherServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "wordsearcher")
	ctx = ctxsetters.WithServiceName(ctx, "QuestionSearcher")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "wordsearcher.QuestionSearcher" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "Search":
		s.serveSearch(ctx, resp, req)
		return
	case "Expand":
		s.serveExpand(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *questionSearcherServer) serveSearch(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveSearchJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveSearchProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *questionSearcherServer) serveSearchJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Search")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(SearchRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the json request could not be decoded"))
		return
	}

	handler := s.QuestionSearcher.Search
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SearchRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SearchRequest) when calling interceptor")
					}
					return s.QuestionSearcher.Search(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *SearchResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *SearchResponse and nil error while calling Search. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true, EmitDefaults: !s.jsonSkipDefaults}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	respBytes := buf.Bytes()
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *questionSearcherServer) serveSearchProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Search")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to read request body"))
		return
	}
	reqContent := new(SearchRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.QuestionSearcher.Search
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SearchRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SearchRequest) when calling interceptor")
					}
					return s.QuestionSearcher.Search(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *SearchResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *SearchResponse and nil error while calling Search. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *questionSearcherServer) serveExpand(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveExpandJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveExpandProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *questionSearcherServer) serveExpandJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Expand")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(SearchResponse)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the json request could not be decoded"))
		return
	}

	handler := s.QuestionSearcher.Expand
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *SearchResponse) (*SearchResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SearchResponse)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SearchResponse) when calling interceptor")
					}
					return s.QuestionSearcher.Expand(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *SearchResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *SearchResponse and nil error while calling Expand. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true, EmitDefaults: !s.jsonSkipDefaults}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	respBytes := buf.Bytes()
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *questionSearcherServer) serveExpandProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Expand")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to read request body"))
		return
	}
	reqContent := new(SearchResponse)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.QuestionSearcher.Expand
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *SearchResponse) (*SearchResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SearchResponse)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SearchResponse) when calling interceptor")
					}
					return s.QuestionSearcher.Expand(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *SearchResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *SearchResponse and nil error while calling Expand. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *questionSearcherServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 0
}

func (s *questionSearcherServer) ProtocGenTwirpVersion() string {
	return "v7.1.0"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *questionSearcherServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "wordsearcher", "QuestionSearcher")
}

// ====================
// Anagrammer Interface
// ====================

type Anagrammer interface {
	// Anagram does a simple anagram search; it can either be
	// build mode or regular (exact) mode.
	// Maybe can add Regex later.
	Anagram(context.Context, *AnagramRequest) (*AnagramResponse, error)

	// BlankChallengeCreator creates blank challenges for Aerolith
	BlankChallengeCreator(context.Context, *BlankChallengeCreateRequest) (*SearchResponse, error)

	// BuildChallengeCreator creates build challenges for Aerolith.
	BuildChallengeCreator(context.Context, *BuildChallengeCreateRequest) (*SearchResponse, error)
}

// ==========================
// Anagrammer Protobuf Client
// ==========================

type anagrammerProtobufClient struct {
	client      HTTPClient
	urls        [3]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewAnagrammerProtobufClient creates a Protobuf client that implements the Anagrammer interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewAnagrammerProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) Anagrammer {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(clientOpts.PathPrefix(), "wordsearcher", "Anagrammer")
	urls := [3]string{
		serviceURL + "Anagram",
		serviceURL + "BlankChallengeCreator",
		serviceURL + "BuildChallengeCreator",
	}

	return &anagrammerProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *anagrammerProtobufClient) Anagram(ctx context.Context, in *AnagramRequest) (*AnagramResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "wordsearcher")
	ctx = ctxsetters.WithServiceName(ctx, "Anagrammer")
	ctx = ctxsetters.WithMethodName(ctx, "Anagram")
	caller := c.callAnagram
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *AnagramRequest) (*AnagramResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*AnagramRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*AnagramRequest) when calling interceptor")
					}
					return c.callAnagram(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AnagramResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AnagramResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *anagrammerProtobufClient) callAnagram(ctx context.Context, in *AnagramRequest) (*AnagramResponse, error) {
	out := new(AnagramResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *anagrammerProtobufClient) BlankChallengeCreator(ctx context.Context, in *BlankChallengeCreateRequest) (*SearchResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "wordsearcher")
	ctx = ctxsetters.WithServiceName(ctx, "Anagrammer")
	ctx = ctxsetters.WithMethodName(ctx, "BlankChallengeCreator")
	caller := c.callBlankChallengeCreator
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *BlankChallengeCreateRequest) (*SearchResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*BlankChallengeCreateRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*BlankChallengeCreateRequest) when calling interceptor")
					}
					return c.callBlankChallengeCreator(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *anagrammerProtobufClient) callBlankChallengeCreator(ctx context.Context, in *BlankChallengeCreateRequest) (*SearchResponse, error) {
	out := new(SearchResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *anagrammerProtobufClient) BuildChallengeCreator(ctx context.Context, in *BuildChallengeCreateRequest) (*SearchResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "wordsearcher")
	ctx = ctxsetters.WithServiceName(ctx, "Anagrammer")
	ctx = ctxsetters.WithMethodName(ctx, "BuildChallengeCreator")
	caller := c.callBuildChallengeCreator
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *BuildChallengeCreateRequest) (*SearchResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*BuildChallengeCreateRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*BuildChallengeCreateRequest) when calling interceptor")
					}
					return c.callBuildChallengeCreator(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *anagrammerProtobufClient) callBuildChallengeCreator(ctx context.Context, in *BuildChallengeCreateRequest) (*SearchResponse, error) {
	out := new(SearchResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ======================
// Anagrammer JSON Client
// ======================

type anagrammerJSONClient struct {
	client      HTTPClient
	urls        [3]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewAnagrammerJSONClient creates a JSON client that implements the Anagrammer interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewAnagrammerJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) Anagrammer {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(clientOpts.PathPrefix(), "wordsearcher", "Anagrammer")
	urls := [3]string{
		serviceURL + "Anagram",
		serviceURL + "BlankChallengeCreator",
		serviceURL + "BuildChallengeCreator",
	}

	return &anagrammerJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *anagrammerJSONClient) Anagram(ctx context.Context, in *AnagramRequest) (*AnagramResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "wordsearcher")
	ctx = ctxsetters.WithServiceName(ctx, "Anagrammer")
	ctx = ctxsetters.WithMethodName(ctx, "Anagram")
	caller := c.callAnagram
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *AnagramRequest) (*AnagramResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*AnagramRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*AnagramRequest) when calling interceptor")
					}
					return c.callAnagram(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AnagramResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AnagramResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *anagrammerJSONClient) callAnagram(ctx context.Context, in *AnagramRequest) (*AnagramResponse, error) {
	out := new(AnagramResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *anagrammerJSONClient) BlankChallengeCreator(ctx context.Context, in *BlankChallengeCreateRequest) (*SearchResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "wordsearcher")
	ctx = ctxsetters.WithServiceName(ctx, "Anagrammer")
	ctx = ctxsetters.WithMethodName(ctx, "BlankChallengeCreator")
	caller := c.callBlankChallengeCreator
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *BlankChallengeCreateRequest) (*SearchResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*BlankChallengeCreateRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*BlankChallengeCreateRequest) when calling interceptor")
					}
					return c.callBlankChallengeCreator(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *anagrammerJSONClient) callBlankChallengeCreator(ctx context.Context, in *BlankChallengeCreateRequest) (*SearchResponse, error) {
	out := new(SearchResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *anagrammerJSONClient) BuildChallengeCreator(ctx context.Context, in *BuildChallengeCreateRequest) (*SearchResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "wordsearcher")
	ctx = ctxsetters.WithServiceName(ctx, "Anagrammer")
	ctx = ctxsetters.WithMethodName(ctx, "BuildChallengeCreator")
	caller := c.callBuildChallengeCreator
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *BuildChallengeCreateRequest) (*SearchResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*BuildChallengeCreateRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*BuildChallengeCreateRequest) when calling interceptor")
					}
					return c.callBuildChallengeCreator(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *anagrammerJSONClient) callBuildChallengeCreator(ctx context.Context, in *BuildChallengeCreateRequest) (*SearchResponse, error) {
	out := new(SearchResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// =========================
// Anagrammer Server Handler
// =========================

type anagrammerServer struct {
	Anagrammer
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
}

// NewAnagrammerServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewAnagrammerServer(svc Anagrammer, opts ...interface{}) TwirpServer {
	serverOpts := twirp.ServerOptions{}
	for _, opt := range opts {
		switch o := opt.(type) {
		case twirp.ServerOption:
			o(&serverOpts)
		case *twirp.ServerHooks: // backwards compatibility, allow to specify hooks as an argument
			twirp.WithServerHooks(o)(&serverOpts)
		case nil: // backwards compatibility, allow nil value for the argument
			continue
		default:
			panic(fmt.Sprintf("Invalid option type %T on NewAnagrammerServer", o))
		}
	}

	return &anagrammerServer{
		Anagrammer:       svc,
		pathPrefix:       serverOpts.PathPrefix(),
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		hooks:            serverOpts.Hooks,
		jsonSkipDefaults: serverOpts.JSONSkipDefaults,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *anagrammerServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// AnagrammerPathPrefix is a convenience constant that could used to identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// that add a "/twirp" prefix by default, and use CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const AnagrammerPathPrefix = "/twirp/wordsearcher.Anagrammer/"

func (s *anagrammerServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "wordsearcher")
	ctx = ctxsetters.WithServiceName(ctx, "Anagrammer")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "wordsearcher.Anagrammer" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "Anagram":
		s.serveAnagram(ctx, resp, req)
		return
	case "BlankChallengeCreator":
		s.serveBlankChallengeCreator(ctx, resp, req)
		return
	case "BuildChallengeCreator":
		s.serveBuildChallengeCreator(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *anagrammerServer) serveAnagram(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveAnagramJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveAnagramProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *anagrammerServer) serveAnagramJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Anagram")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(AnagramRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the json request could not be decoded"))
		return
	}

	handler := s.Anagrammer.Anagram
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *AnagramRequest) (*AnagramResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*AnagramRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*AnagramRequest) when calling interceptor")
					}
					return s.Anagrammer.Anagram(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AnagramResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AnagramResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *AnagramResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AnagramResponse and nil error while calling Anagram. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true, EmitDefaults: !s.jsonSkipDefaults}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	respBytes := buf.Bytes()
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *anagrammerServer) serveAnagramProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Anagram")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to read request body"))
		return
	}
	reqContent := new(AnagramRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Anagrammer.Anagram
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *AnagramRequest) (*AnagramResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*AnagramRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*AnagramRequest) when calling interceptor")
					}
					return s.Anagrammer.Anagram(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AnagramResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AnagramResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *AnagramResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AnagramResponse and nil error while calling Anagram. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *anagrammerServer) serveBlankChallengeCreator(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveBlankChallengeCreatorJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveBlankChallengeCreatorProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *anagrammerServer) serveBlankChallengeCreatorJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "BlankChallengeCreator")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(BlankChallengeCreateRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the json request could not be decoded"))
		return
	}

	handler := s.Anagrammer.BlankChallengeCreator
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *BlankChallengeCreateRequest) (*SearchResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*BlankChallengeCreateRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*BlankChallengeCreateRequest) when calling interceptor")
					}
					return s.Anagrammer.BlankChallengeCreator(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *SearchResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *SearchResponse and nil error while calling BlankChallengeCreator. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true, EmitDefaults: !s.jsonSkipDefaults}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	respBytes := buf.Bytes()
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *anagrammerServer) serveBlankChallengeCreatorProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "BlankChallengeCreator")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to read request body"))
		return
	}
	reqContent := new(BlankChallengeCreateRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Anagrammer.BlankChallengeCreator
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *BlankChallengeCreateRequest) (*SearchResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*BlankChallengeCreateRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*BlankChallengeCreateRequest) when calling interceptor")
					}
					return s.Anagrammer.BlankChallengeCreator(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *SearchResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *SearchResponse and nil error while calling BlankChallengeCreator. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *anagrammerServer) serveBuildChallengeCreator(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveBuildChallengeCreatorJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveBuildChallengeCreatorProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *anagrammerServer) serveBuildChallengeCreatorJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "BuildChallengeCreator")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(BuildChallengeCreateRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the json request could not be decoded"))
		return
	}

	handler := s.Anagrammer.BuildChallengeCreator
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *BuildChallengeCreateRequest) (*SearchResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*BuildChallengeCreateRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*BuildChallengeCreateRequest) when calling interceptor")
					}
					return s.Anagrammer.BuildChallengeCreator(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *SearchResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *SearchResponse and nil error while calling BuildChallengeCreator. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true, EmitDefaults: !s.jsonSkipDefaults}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	respBytes := buf.Bytes()
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *anagrammerServer) serveBuildChallengeCreatorProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "BuildChallengeCreator")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to read request body"))
		return
	}
	reqContent := new(BuildChallengeCreateRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Anagrammer.BuildChallengeCreator
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *BuildChallengeCreateRequest) (*SearchResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*BuildChallengeCreateRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*BuildChallengeCreateRequest) when calling interceptor")
					}
					return s.Anagrammer.BuildChallengeCreator(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *SearchResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *SearchResponse and nil error while calling BuildChallengeCreator. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *anagrammerServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 1
}

func (s *anagrammerServer) ProtocGenTwirpVersion() string {
	return "v7.1.0"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *anagrammerServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "wordsearcher", "Anagrammer")
}

// =====
// Utils
// =====

// HTTPClient is the interface used by generated clients to send HTTP requests.
// It is fulfilled by *(net/http).Client, which is sufficient for most users.
// Users can provide their own implementation for special retry policies.
//
// HTTPClient implementations should not follow redirects. Redirects are
// automatically disabled if *(net/http).Client is passed to client
// constructors. See the withoutRedirects function in this file for more
// details.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// TwirpServer is the interface generated server structs will support: they're
// HTTP handlers with additional methods for accessing metadata about the
// service. Those accessors are a low-level API for building reflection tools.
// Most people can think of TwirpServers as just http.Handlers.
type TwirpServer interface {
	http.Handler

	// ServiceDescriptor returns gzipped bytes describing the .proto file that
	// this service was generated from. Once unzipped, the bytes can be
	// unmarshalled as a
	// github.com/golang/protobuf/protoc-gen-go/descriptor.FileDescriptorProto.
	//
	// The returned integer is the index of this particular service within that
	// FileDescriptorProto's 'Service' slice of ServiceDescriptorProtos. This is a
	// low-level field, expected to be used for reflection.
	ServiceDescriptor() ([]byte, int)

	// ProtocGenTwirpVersion is the semantic version string of the version of
	// twirp used to generate this file.
	ProtocGenTwirpVersion() string

	// PathPrefix returns the HTTP URL path prefix for all methods handled by this
	// service. This can be used with an HTTP mux to route Twirp requests.
	// The path prefix is in the form: "/<prefix>/<package>.<Service>/"
	// that is, everything in a Twirp route except for the <Method> at the end.
	PathPrefix() string
}

// WriteError writes an HTTP response with a valid Twirp error format (code, msg, meta).
// Useful outside of the Twirp server (e.g. http middleware), but does not trigger hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func WriteError(resp http.ResponseWriter, err error) {
	writeError(context.Background(), resp, err, nil)
}

// writeError writes Twirp errors in the response and triggers hooks.
func writeError(ctx context.Context, resp http.ResponseWriter, err error, hooks *twirp.ServerHooks) {
	// Non-twirp errors are wrapped as Internal (default)
	twerr, ok := err.(twirp.Error)
	if !ok {
		twerr = twirp.InternalErrorWith(err)
	}

	statusCode := twirp.ServerHTTPStatusFromErrorCode(twerr.Code())
	ctx = ctxsetters.WithStatusCode(ctx, statusCode)
	ctx = callError(ctx, hooks, twerr)

	respBody := marshalErrorToJSON(twerr)

	resp.Header().Set("Content-Type", "application/json") // Error responses are always JSON
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBody)))
	resp.WriteHeader(statusCode) // set HTTP status code and send response

	_, writeErr := resp.Write(respBody)
	if writeErr != nil {
		// We have three options here. We could log the error, call the Error
		// hook, or just silently ignore the error.
		//
		// Logging is unacceptable because we don't have a user-controlled
		// logger; writing out to stderr without permission is too rude.
		//
		// Calling the Error hook would confuse users: it would mean the Error
		// hook got called twice for one request, which is likely to lead to
		// duplicated log messages and metrics, no matter how well we document
		// the behavior.
		//
		// Silently ignoring the error is our least-bad option. It's highly
		// likely that the connection is broken and the original 'err' says
		// so anyway.
		_ = writeErr
	}

	callResponseSent(ctx, hooks)
}

// sanitizeBaseURL parses the the baseURL, and adds the "http" scheme if needed.
// If the URL is unparsable, the baseURL is returned unchaged.
func sanitizeBaseURL(baseURL string) string {
	u, err := url.Parse(baseURL)
	if err != nil {
		return baseURL // invalid URL will fail later when making requests
	}
	if u.Scheme == "" {
		u.Scheme = "http"
	}
	return u.String()
}

// baseServicePath composes the path prefix for the service (without <Method>).
// e.g.: baseServicePath("/twirp", "my.pkg", "MyService")
//       returns => "/twirp/my.pkg.MyService/"
// e.g.: baseServicePath("", "", "MyService")
//       returns => "/MyService/"
func baseServicePath(prefix, pkg, service string) string {
	fullServiceName := service
	if pkg != "" {
		fullServiceName = pkg + "." + service
	}
	return path.Join("/", prefix, fullServiceName) + "/"
}

// parseTwirpPath extracts path components form a valid Twirp route.
// Expected format: "[<prefix>]/<package>.<Service>/<Method>"
// e.g.: prefix, pkgService, method := parseTwirpPath("/twirp/pkg.Svc/MakeHat")
func parseTwirpPath(path string) (string, string, string) {
	parts := strings.Split(path, "/")
	if len(parts) < 2 {
		return "", "", ""
	}
	method := parts[len(parts)-1]
	pkgService := parts[len(parts)-2]
	prefix := strings.Join(parts[0:len(parts)-2], "/")
	return prefix, pkgService, method
}

// getCustomHTTPReqHeaders retrieves a copy of any headers that are set in
// a context through the twirp.WithHTTPRequestHeaders function.
// If there are no headers set, or if they have the wrong type, nil is returned.
func getCustomHTTPReqHeaders(ctx context.Context) http.Header {
	header, ok := twirp.HTTPRequestHeaders(ctx)
	if !ok || header == nil {
		return nil
	}
	copied := make(http.Header)
	for k, vv := range header {
		if vv == nil {
			copied[k] = nil
			continue
		}
		copied[k] = make([]string, len(vv))
		copy(copied[k], vv)
	}
	return copied
}

// newRequest makes an http.Request from a client, adding common headers.
func newRequest(ctx context.Context, url string, reqBody io.Reader, contentType string) (*http.Request, error) {
	req, err := http.NewRequest("POST", url, reqBody)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if customHeader := getCustomHTTPReqHeaders(ctx); customHeader != nil {
		req.Header = customHeader
	}
	req.Header.Set("Accept", contentType)
	req.Header.Set("Content-Type", contentType)
	req.Header.Set("Twirp-Version", "v7.1.0")
	return req, nil
}

// JSON serialization for errors
type twerrJSON struct {
	Code string            `json:"code"`
	Msg  string            `json:"msg"`
	Meta map[string]string `json:"meta,omitempty"`
}

// marshalErrorToJSON returns JSON from a twirp.Error, that can be used as HTTP error response body.
// If serialization fails, it will use a descriptive Internal error instead.
func marshalErrorToJSON(twerr twirp.Error) []byte {
	// make sure that msg is not too large
	msg := twerr.Msg()
	if len(msg) > 1e6 {
		msg = msg[:1e6]
	}

	tj := twerrJSON{
		Code: string(twerr.Code()),
		Msg:  msg,
		Meta: twerr.MetaMap(),
	}

	buf, err := json.Marshal(&tj)
	if err != nil {
		buf = []byte("{\"type\": \"" + twirp.Internal + "\", \"msg\": \"There was an error but it could not be serialized into JSON\"}") // fallback
	}

	return buf
}

// errorFromResponse builds a twirp.Error from a non-200 HTTP response.
// If the response has a valid serialized Twirp error, then it's returned.
// If not, the response status code is used to generate a similar twirp
// error. See twirpErrorFromIntermediary for more info on intermediary errors.
func errorFromResponse(resp *http.Response) twirp.Error {
	statusCode := resp.StatusCode
	statusText := http.StatusText(statusCode)

	if isHTTPRedirect(statusCode) {
		// Unexpected redirect: it must be an error from an intermediary.
		// Twirp clients don't follow redirects automatically, Twirp only handles
		// POST requests, redirects should only happen on GET and HEAD requests.
		location := resp.Header.Get("Location")
		msg := fmt.Sprintf("unexpected HTTP status code %d %q received, Location=%q", statusCode, statusText, location)
		return twirpErrorFromIntermediary(statusCode, msg, location)
	}

	respBodyBytes, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return wrapInternal(err, "failed to read server error response body")
	}

	var tj twerrJSON
	dec := json.NewDecoder(bytes.NewReader(respBodyBytes))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&tj); err != nil || tj.Code == "" {
		// Invalid JSON response; it must be an error from an intermediary.
		msg := fmt.Sprintf("Error from intermediary with HTTP status code %d %q", statusCode, statusText)
		return twirpErrorFromIntermediary(statusCode, msg, string(respBodyBytes))
	}

	errorCode := twirp.ErrorCode(tj.Code)
	if !twirp.IsValidErrorCode(errorCode) {
		msg := "invalid type returned from server error response: " + tj.Code
		return twirp.InternalError(msg).WithMeta("body", string(respBodyBytes))
	}

	twerr := twirp.NewError(errorCode, tj.Msg)
	for k, v := range tj.Meta {
		twerr = twerr.WithMeta(k, v)
	}
	return twerr
}

// twirpErrorFromIntermediary maps HTTP errors from non-twirp sources to twirp errors.
// The mapping is similar to gRPC: https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md.
// Returned twirp Errors have some additional metadata for inspection.
func twirpErrorFromIntermediary(status int, msg string, bodyOrLocation string) twirp.Error {
	var code twirp.ErrorCode
	if isHTTPRedirect(status) { // 3xx
		code = twirp.Internal
	} else {
		switch status {
		case 400: // Bad Request
			code = twirp.Internal
		case 401: // Unauthorized
			code = twirp.Unauthenticated
		case 403: // Forbidden
			code = twirp.PermissionDenied
		case 404: // Not Found
			code = twirp.BadRoute
		case 429: // Too Many Requests
			code = twirp.ResourceExhausted
		case 502, 503, 504: // Bad Gateway, Service Unavailable, Gateway Timeout
			code = twirp.Unavailable
		default: // All other codes
			code = twirp.Unknown
		}
	}

	twerr := twirp.NewError(code, msg)
	twerr = twerr.WithMeta("http_error_from_intermediary", "true") // to easily know if this error was from intermediary
	twerr = twerr.WithMeta("status_code", strconv.Itoa(status))
	if isHTTPRedirect(status) {
		twerr = twerr.WithMeta("location", bodyOrLocation)
	} else {
		twerr = twerr.WithMeta("body", bodyOrLocation)
	}
	return twerr
}

func isHTTPRedirect(status int) bool {
	return status >= 300 && status <= 399
}

// wrapInternal wraps an error with a prefix as an Internal error.
// The original error cause is accessible by github.com/pkg/errors.Cause.
func wrapInternal(err error, prefix string) twirp.Error {
	return twirp.InternalErrorWith(&wrappedError{prefix: prefix, cause: err})
}

type wrappedError struct {
	prefix string
	cause  error
}

func (e *wrappedError) Error() string { return e.prefix + ": " + e.cause.Error() }
func (e *wrappedError) Unwrap() error { return e.cause } // for go1.13 + errors.Is/As
func (e *wrappedError) Cause() error  { return e.cause } // for github.com/pkg/errors

// ensurePanicResponses makes sure that rpc methods causing a panic still result in a Twirp Internal
// error response (status 500), and error hooks are properly called with the panic wrapped as an error.
// The panic is re-raised so it can be handled normally with middleware.
func ensurePanicResponses(ctx context.Context, resp http.ResponseWriter, hooks *twirp.ServerHooks) {
	if r := recover(); r != nil {
		// Wrap the panic as an error so it can be passed to error hooks.
		// The original error is accessible from error hooks, but not visible in the response.
		err := errFromPanic(r)
		twerr := &internalWithCause{msg: "Internal service panic", cause: err}
		// Actually write the error
		writeError(ctx, resp, twerr, hooks)
		// If possible, flush the error to the wire.
		f, ok := resp.(http.Flusher)
		if ok {
			f.Flush()
		}

		panic(r)
	}
}

// errFromPanic returns the typed error if the recovered panic is an error, otherwise formats as error.
func errFromPanic(p interface{}) error {
	if err, ok := p.(error); ok {
		return err
	}
	return fmt.Errorf("panic: %v", p)
}

// internalWithCause is a Twirp Internal error wrapping an original error cause,
// but the original error message is not exposed on Msg(). The original error
// can be checked with go1.13+ errors.Is/As, and also by (github.com/pkg/errors).Unwrap
type internalWithCause struct {
	msg   string
	cause error
}

func (e *internalWithCause) Unwrap() error                               { return e.cause } // for go1.13 + errors.Is/As
func (e *internalWithCause) Cause() error                                { return e.cause } // for github.com/pkg/errors
func (e *internalWithCause) Error() string                               { return e.msg + ": " + e.cause.Error() }
func (e *internalWithCause) Code() twirp.ErrorCode                       { return twirp.Internal }
func (e *internalWithCause) Msg() string                                 { return e.msg }
func (e *internalWithCause) Meta(key string) string                      { return "" }
func (e *internalWithCause) MetaMap() map[string]string                  { return nil }
func (e *internalWithCause) WithMeta(key string, val string) twirp.Error { return e }

// malformedRequestError is used when the twirp server cannot unmarshal a request
func malformedRequestError(msg string) twirp.Error {
	return twirp.NewError(twirp.Malformed, msg)
}

// badRouteError is used when the twirp server cannot route a request
func badRouteError(msg string, method, url string) twirp.Error {
	err := twirp.NewError(twirp.BadRoute, msg)
	err = err.WithMeta("twirp_invalid_route", method+" "+url)
	return err
}

// withoutRedirects makes sure that the POST request can not be redirected.
// The standard library will, by default, redirect requests (including POSTs) if it gets a 302 or
// 303 response, and also 301s in go1.8. It redirects by making a second request, changing the
// method to GET and removing the body. This produces very confusing error messages, so instead we
// set a redirect policy that always errors. This stops Go from executing the redirect.
//
// We have to be a little careful in case the user-provided http.Client has its own CheckRedirect
// policy - if so, we'll run through that policy first.
//
// Because this requires modifying the http.Client, we make a new copy of the client and return it.
func withoutRedirects(in *http.Client) *http.Client {
	copy := *in
	copy.CheckRedirect = func(req *http.Request, via []*http.Request) error {
		if in.CheckRedirect != nil {
			// Run the input's redirect if it exists, in case it has side effects, but ignore any error it
			// returns, since we want to use ErrUseLastResponse.
			err := in.CheckRedirect(req, via)
			_ = err // Silly, but this makes sure generated code passes errcheck -blank, which some people use.
		}
		return http.ErrUseLastResponse
	}
	return &copy
}

// doProtobufRequest makes a Protobuf request to the remote Twirp service.
func doProtobufRequest(ctx context.Context, client HTTPClient, hooks *twirp.ClientHooks, url string, in, out proto.Message) (_ context.Context, err error) {
	reqBodyBytes, err := proto.Marshal(in)
	if err != nil {
		return ctx, wrapInternal(err, "failed to marshal proto request")
	}
	reqBody := bytes.NewBuffer(reqBodyBytes)
	if err = ctx.Err(); err != nil {
		return ctx, wrapInternal(err, "aborted because context was done")
	}

	req, err := newRequest(ctx, url, reqBody, "application/protobuf")
	if err != nil {
		return ctx, wrapInternal(err, "could not build request")
	}
	ctx, err = callClientRequestPrepared(ctx, hooks, req)
	if err != nil {
		return ctx, err
	}

	req = req.WithContext(ctx)
	resp, err := client.Do(req)
	if err != nil {
		return ctx, wrapInternal(err, "failed to do request")
	}

	defer func() {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = wrapInternal(cerr, "failed to close response body")
		}
	}()

	if err = ctx.Err(); err != nil {
		return ctx, wrapInternal(err, "aborted because context was done")
	}

	if resp.StatusCode != 200 {
		return ctx, errorFromResponse(resp)
	}

	respBodyBytes, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return ctx, wrapInternal(err, "failed to read response body")
	}
	if err = ctx.Err(); err != nil {
		return ctx, wrapInternal(err, "aborted because context was done")
	}

	if err = proto.Unmarshal(respBodyBytes, out); err != nil {
		return ctx, wrapInternal(err, "failed to unmarshal proto response")
	}
	return ctx, nil
}

// doJSONRequest makes a JSON request to the remote Twirp service.
func doJSONRequest(ctx context.Context, client HTTPClient, hooks *twirp.ClientHooks, url string, in, out proto.Message) (_ context.Context, err error) {
	reqBody := bytes.NewBuffer(nil)
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(reqBody, in); err != nil {
		return ctx, wrapInternal(err, "failed to marshal json request")
	}
	if err = ctx.Err(); err != nil {
		return ctx, wrapInternal(err, "aborted because context was done")
	}

	req, err := newRequest(ctx, url, reqBody, "application/json")
	if err != nil {
		return ctx, wrapInternal(err, "could not build request")
	}
	ctx, err = callClientRequestPrepared(ctx, hooks, req)
	if err != nil {
		return ctx, err
	}

	req = req.WithContext(ctx)
	resp, err := client.Do(req)
	if err != nil {
		return ctx, wrapInternal(err, "failed to do request")
	}

	defer func() {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = wrapInternal(cerr, "failed to close response body")
		}
	}()

	if err = ctx.Err(); err != nil {
		return ctx, wrapInternal(err, "aborted because context was done")
	}

	if resp.StatusCode != 200 {
		return ctx, errorFromResponse(resp)
	}

	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(resp.Body, out); err != nil {
		return ctx, wrapInternal(err, "failed to unmarshal json response")
	}
	if err = ctx.Err(); err != nil {
		return ctx, wrapInternal(err, "aborted because context was done")
	}
	return ctx, nil
}

// Call twirp.ServerHooks.RequestReceived if the hook is available
func callRequestReceived(ctx context.Context, h *twirp.ServerHooks) (context.Context, error) {
	if h == nil || h.RequestReceived == nil {
		return ctx, nil
	}
	return h.RequestReceived(ctx)
}

// Call twirp.ServerHooks.RequestRouted if the hook is available
func callRequestRouted(ctx context.Context, h *twirp.ServerHooks) (context.Context, error) {
	if h == nil || h.RequestRouted == nil {
		return ctx, nil
	}
	return h.RequestRouted(ctx)
}

// Call twirp.ServerHooks.ResponsePrepared if the hook is available
func callResponsePrepared(ctx context.Context, h *twirp.ServerHooks) context.Context {
	if h == nil || h.ResponsePrepared == nil {
		return ctx
	}
	return h.ResponsePrepared(ctx)
}

// Call twirp.ServerHooks.ResponseSent if the hook is available
func callResponseSent(ctx context.Context, h *twirp.ServerHooks) {
	if h == nil || h.ResponseSent == nil {
		return
	}
	h.ResponseSent(ctx)
}

// Call twirp.ServerHooks.Error if the hook is available
func callError(ctx context.Context, h *twirp.ServerHooks, err twirp.Error) context.Context {
	if h == nil || h.Error == nil {
		return ctx
	}
	return h.Error(ctx, err)
}

func callClientResponseReceived(ctx context.Context, h *twirp.ClientHooks) {
	if h == nil || h.ResponseReceived == nil {
		return
	}
	h.ResponseReceived(ctx)
}

func callClientRequestPrepared(ctx context.Context, h *twirp.ClientHooks, req *http.Request) (context.Context, error) {
	if h == nil || h.RequestPrepared == nil {
		return ctx, nil
	}
	return h.RequestPrepared(ctx, req)
}

func callClientError(ctx context.Context, h *twirp.ClientHooks, err twirp.Error) {
	if h == nil || h.Error == nil {
		return
	}
	h.Error(ctx, err)
}

var twirpFileDescriptor0 = []byte{
	// 1316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0x4d, 0x73, 0xda, 0x46,
	0x18, 0xb6, 0xcc, 0x87, 0xd1, 0x8b, 0xc1, 0xf2, 0x36, 0x1f, 0x8c, 0x93, 0x34, 0x2e, 0x99, 0x34,
	0x64, 0xa6, 0x63, 0x4f, 0x49, 0xd3, 0x5e, 0x72, 0x11, 0x58, 0x06, 0x4d, 0x84, 0xe4, 0xae, 0xc0,
	0x76, 0x7a, 0x51, 0x05, 0xc8, 0x46, 0x13, 0x24, 0x11, 0x49, 0xa4, 0xf8, 0x77, 0xf4, 0xd2, 0x4b,
	0x7f, 0x44, 0x7f, 0x48, 0x7b, 0xec, 0x3f, 0xe9, 0x74, 0xa6, 0xa7, 0xce, 0x7e, 0x08, 0x24, 0xd7,
	0xc1, 0x9e, 0xde, 0x76, 0x9f, 0x7d, 0xde, 0xe7, 0xfd, 0x64, 0x57, 0xc0, 0xd3, 0x70, 0x36, 0x3a,
	0xfc, 0x29, 0x08, 0xc7, 0x91, 0x63, 0x87, 0xa3, 0x89, 0x13, 0x1e, 0x26, 0x8b, 0x83, 0x59, 0x18,
	0xc4, 0x01, 0xda, 0x4e, 0x1f, 0xd6, 0xff, 0x12, 0x40, 0x94, 0xa7, 0xb3, 0x89, 0x7d, 0x19, 0xda,
	0x1e, 0x7a, 0x0c, 0xa2, 0x9d, 0x6c, 0x6a, 0xc2, 0xbe, 0xd0, 0x10, 0xf1, 0x0a, 0x40, 0x0d, 0x28,
	0x50, 0xdb, 0xda, 0xe6, 0x7e, 0xae, 0x51, 0x6e, 0xa2, 0x83, 0xb4, 0xd2, 0xc1, 0x59, 0x10, 0x8e,
	0x31, 0x23, 0xa0, 0x3a, 0x6c, 0x3b, 0x8b, 0x99, 0xed, 0x8f, 0x9d, 0x31, 0x76, 0x66, 0x61, 0x2d,
	0xb7, 0x2f, 0x34, 0x4a, 0x38, 0x83, 0xa1, 0x07, 0x50, 0x9c, 0x3a, 0xfe, 0x65, 0x3c, 0xa9, 0xe5,
	0xf7, 0x85, 0x46, 0x01, 0xf3, 0x1d, 0xda, 0x87, 0xf2, 0x2c, 0x0c, 0x86, 0xf6, 0xd0, 0x9d, 0xba,
	0xf1, 0x55, 0xad, 0x40, 0x0f, 0xd3, 0x10, 0x51, 0x1f, 0x05, 0xde, 0xd0, 0xf5, 0xed, 0xd8, 0x0d,
	0xfc, 0xa8, 0x56, 0xdc, 0x17, 0x1a, 0x39, 0x9c, 0xc1, 0xd0, 0xe7, 0x00, 0x63, 0xf7, 0xe2, 0xc2,
	0x1d, 0xcd, 0xa7, 0xf1, 0x55, 0x6d, 0x8b, 0x8a, 0xa4, 0x90, 0xfa, 0xcf, 0x9b, 0x90, 0x27, 0x11,
	0x23, 0x04, 0x79, 0x12, 0x33, 0xcf, 0x96, 0xae, 0xb3, 0x65, 0xd8, 0xbc, 0x5e, 0x06, 0x22, 0xed,
	0x5c, 0xb8, 0xbe, 0x4b, 0x3c, 0xd1, 0xd4, 0x44, 0x9c, 0x42, 0xd0, 0x53, 0x28, 0x5f, 0x84, 0x81,
	0x1f, 0x5b, 0x93, 0x20, 0x78, 0x1f, 0xd1, 0xec, 0x44, 0x0c, 0x14, 0xea, 0x12, 0x04, 0x3d, 0x01,
	0x18, 0xda, 0xa3, 0xf7, 0xfc, 0xbc, 0xc0, 0xf4, 0x09, 0xc2, 0x8e, 0x5f, 0xc0, 0xce, 0xd4, 0x59,
	0xb8, 0xa3, 0xc0, 0xb7, 0xa2, 0x2b, 0x6f, 0x18, 0x4c, 0x59, 0x86, 0x22, 0xae, 0x72, 0xd8, 0x64,
	0x28, 0x6a, 0x80, 0xe4, 0xfa, 0xbe, 0x13, 0x5a, 0x2b, 0x77, 0x34, 0xd3, 0x12, 0xae, 0x52, 0xfc,
	0x38, 0x71, 0x89, 0xbe, 0x84, 0x1d, 0xc6, 0x5c, 0xfa, 0xad, 0x95, 0x28, 0xb1, 0x42, 0xe1, 0x16,
	0xf7, 0x5d, 0xff, 0x43, 0x84, 0x8a, 0x49, 0x1b, 0x8a, 0x9d, 0x0f, 0x73, 0x27, 0x8a, 0xd1, 0x5b,
	0xd8, 0x66, 0x1d, 0x9e, 0xd9, 0xa1, 0xed, 0x45, 0x35, 0x81, 0xb6, 0xfe, 0x45, 0xb6, 0xf5, 0x19,
	0x13, 0xbe, 0x3b, 0x21, 0x7c, 0x9c, 0x31, 0x26, 0x2d, 0x67, 0x23, 0x40, 0x8b, 0x5a, 0xc2, 0x7c,
	0xb7, 0xf7, 0x15, 0x14, 0x7b, 0xae, 0xdf, 0xb3, 0x17, 0x48, 0x82, 0x9c, 0xe7, 0xfa, 0xb4, 0x19,
	0x05, 0x4c, 0x96, 0x14, 0xb1, 0x17, 0xd4, 0x80, 0x20, 0xf6, 0x62, 0xef, 0x19, 0x94, 0xcd, 0x38,
	0x74, 0xfd, 0xcb, 0x53, 0x7b, 0x3a, 0x77, 0xd0, 0x3d, 0x28, 0x7c, 0x24, 0x0b, 0xde, 0x41, 0xb6,
	0xd9, 0x7b, 0x9e, 0x90, 0xe4, 0x30, 0xb4, 0xaf, 0x88, 0x67, 0x8a, 0xb3, 0x04, 0x44, 0xcc, 0x77,
	0x84, 0xa6, 0xcf, 0xbd, 0xa1, 0x13, 0xde, 0x44, 0x2b, 0x2c, 0x69, 0xcf, 0x12, 0xda, 0x0d, 0x2e,
	0x0b, 0x89, 0xcb, 0x3f, 0x73, 0x50, 0x4e, 0xe5, 0x8e, 0xda, 0x20, 0x8e, 0x02, 0x7f, 0xcc, 0xc6,
	0x84, 0x30, 0xab, 0xcd, 0xe7, 0xeb, 0xea, 0xd6, 0x4e, 0xc8, 0x78, 0x65, 0x87, 0xde, 0x40, 0xd1,
	0x73, 0xfd, 0xa4, 0x02, 0xe5, 0x66, 0x7d, 0x9d, 0x02, 0x2b, 0x62, 0x77, 0x03, 0x73, 0x1b, 0xf4,
	0x16, 0xca, 0x11, 0xad, 0x02, 0x0b, 0x37, 0x47, 0x25, 0xd6, 0x37, 0x6f, 0x55, 0xd9, 0xee, 0x06,
	0x4e, 0x5b, 0xaf, 0xc4, 0x6c, 0x52, 0x2b, 0x3a, 0xd7, 0x77, 0x12, 0xa3, 0xa5, 0x5d, 0x89, 0x51,
	0x6b, 0x22, 0xe6, 0xd3, 0x8a, 0x32, 0xb1, 0xc2, 0xed, 0x62, 0xa9, 0x3e, 0x11, 0xb1, 0x94, 0xf5,
	0x4a, 0x8c, 0xa5, 0x59, 0xbc, 0xab, 0xd8, 0x32, 0xcd, 0x94, 0x75, 0x4b, 0x82, 0xea, 0xb2, 0xfc,
	0x74, 0x6e, 0xeb, 0xff, 0x6c, 0x82, 0xb8, 0x6c, 0x0e, 0x2a, 0xc3, 0x96, 0xa6, 0x9c, 0xab, 0x6d,
	0x43, 0x97, 0x36, 0x10, 0x40, 0x51, 0x53, 0xf4, 0x4e, 0xbf, 0x2b, 0x09, 0xe8, 0x3e, 0xec, 0x9e,
	0x60, 0xa3, 0x25, 0xb7, 0x54, 0x4d, 0xed, 0xbf, 0xb3, 0xb0, 0xac, 0x77, 0x14, 0x69, 0x13, 0xdd,
	0x03, 0x29, 0x0d, 0x6b, 0xaa, 0xd9, 0x97, 0x72, 0xd7, 0xc9, 0x9a, 0xda, 0x53, 0xfb, 0x52, 0x1e,
	0x3d, 0x00, 0xa4, 0x0f, 0x7a, 0x2d, 0x05, 0x5b, 0xc6, 0xb1, 0x25, 0xeb, 0x72, 0x07, 0xcb, 0x3d,
	0x53, 0x2a, 0x10, 0x91, 0x15, 0x7e, 0x6a, 0x9c, 0x29, 0x9a, 0x29, 0x15, 0xd1, 0x36, 0x94, 0xba,
	0xb2, 0x69, 0xf5, 0xe5, 0x8e, 0x29, 0x6d, 0xa1, 0x1d, 0x28, 0x9f, 0x18, 0xaa, 0xde, 0xb7, 0x4e,
	0x65, 0x6d, 0xa0, 0x48, 0x25, 0x62, 0xd4, 0x93, 0xfb, 0xed, 0xae, 0xaa, 0x77, 0x12, 0x2d, 0x49,
	0x44, 0x08, 0xaa, 0xb2, 0x76, 0xd2, 0xa5, 0x5b, 0x16, 0x0d, 0x10, 0x4c, 0x37, 0xfa, 0x96, 0xaa,
	0x5b, 0x49, 0x6a, 0x65, 0x24, 0x42, 0x01, 0x2b, 0x1d, 0xe5, 0x5c, 0xda, 0x46, 0x15, 0x10, 0xcf,
	0x0c, 0x7c, 0xc4, 0xd8, 0x15, 0xf4, 0x10, 0x3e, 0x33, 0x55, 0xbd, 0xa3, 0x29, 0xcc, 0x93, 0xc5,
	0x2b, 0x50, 0xa5, 0x32, 0x83, 0x9e, 0xd5, 0x3f, 0x33, 0xac, 0x96, 0x26, 0xeb, 0x6f, 0x4d, 0x69,
	0x07, 0xed, 0x42, 0xa5, 0x27, 0x9f, 0x5b, 0xa6, 0xa1, 0x0d, 0xfa, 0xaa, 0xa1, 0x9b, 0x92, 0x44,
	0xe2, 0x3a, 0x52, 0x8f, 0x8f, 0xd5, 0xf6, 0x40, 0x5b, 0xd6, 0x69, 0x97, 0x56, 0x44, 0x93, 0xdf,
	0x65, 0xcb, 0x87, 0xea, 0x6f, 0x60, 0x57, 0x0f, 0x62, 0xd5, 0xd7, 0x9c, 0xc5, 0xaa, 0x07, 0xbb,
	0x50, 0x31, 0xfa, 0x5d, 0x05, 0x5b, 0x8a, 0xde, 0xd1, 0x54, 0xb3, 0x2b, 0x6d, 0xb0, 0x32, 0x2b,
	0xa7, 0xaa, 0x31, 0x30, 0xad, 0x53, 0x05, 0x9b, 0xaa, 0xa1, 0x4b, 0x42, 0x7d, 0x04, 0xd5, 0xa4,
	0xf1, 0xd1, 0x2c, 0xf0, 0x23, 0x07, 0x7d, 0x07, 0xb0, 0xbc, 0xca, 0x93, 0xeb, 0xec, 0x61, 0x76,
	0x54, 0x96, 0xef, 0x21, 0x4e, 0x51, 0x51, 0x0d, 0xb6, 0xf8, 0xfd, 0xcb, 0x9f, 0x84, 0x64, 0x5b,
	0xff, 0x4d, 0x80, 0xaa, 0xec, 0x33, 0x0b, 0x7e, 0x6d, 0xa6, 0xc8, 0x42, 0x86, 0xcc, 0x4e, 0xe2,
	0xd8, 0x09, 0xa3, 0x95, 0x0c, 0xdd, 0xa2, 0xd7, 0x90, 0xf7, 0x82, 0x31, 0xfb, 0x95, 0x56, 0x9b,
	0x5f, 0x5c, 0x8b, 0x29, 0xa3, 0x7f, 0xd0, 0x0b, 0xc6, 0x0e, 0xa6, 0xf4, 0xd4, 0xa5, 0x9a, 0x4f,
	0x5f, 0xaa, 0xf5, 0xc7, 0x90, 0x27, 0x2c, 0xd2, 0x47, 0xe5, 0x5c, 0x6e, 0xf7, 0xa5, 0x0d, 0xb2,
	0x6c, 0x0d, 0x54, 0xed, 0x48, 0x12, 0xea, 0xe7, 0xb0, 0xb3, 0x94, 0xe4, 0x95, 0x59, 0x3e, 0xef,
	0xc2, 0x6d, 0xcf, 0xfb, 0x23, 0x10, 0xfd, 0xb9, 0x67, 0x25, 0x1f, 0x03, 0xe4, 0x0e, 0x2c, 0xf9,
	0x73, 0x8f, 0x50, 0xa2, 0xfa, 0xef, 0x02, 0x3c, 0x6a, 0x4d, 0x6d, 0xff, 0x7d, 0x7b, 0x62, 0x4f,
	0xc9, 0x9b, 0xee, 0xb4, 0x43, 0xc7, 0x8e, 0x9d, 0xdb, 0x4b, 0xf3, 0x0c, 0x2a, 0x44, 0x96, 0xd2,
	0xe8, 0xc3, 0xce, 0xa4, 0xb7, 0xfd, 0xb9, 0xf7, 0x7d, 0x82, 0x11, 0x92, 0x67, 0x2f, 0xac, 0x28,
	0x98, 0xce, 0x19, 0x29, 0xc7, 0x48, 0x9e, 0xbd, 0x30, 0x13, 0x0c, 0xbd, 0x84, 0x5d, 0x1a, 0xa0,
	0x1b, 0x4f, 0xac, 0xa6, 0x35, 0x24, 0xd1, 0x44, 0xfc, 0x33, 0xa3, 0x4a, 0x02, 0x75, 0xe3, 0x49,
	0x93, 0xc6, 0x18, 0x91, 0xd7, 0x9a, 0xe4, 0x61, 0xf1, 0x6f, 0x11, 0xf6, 0xb9, 0x01, 0x04, 0xd2,
	0x28, 0x52, 0xff, 0x9b, 0xe4, 0x33, 0x77, 0xa7, 0xe3, 0xff, 0x93, 0x8f, 0xe7, 0xfa, 0xa9, 0x50,
	0x79, 0x3e, 0x9e, 0xeb, 0xaf, 0x42, 0xbd, 0x53, 0x3e, 0x4f, 0x00, 0x88, 0x52, 0xe6, 0x7b, 0x49,
	0xf4, 0x5c, 0x9f, 0x85, 0x48, 0x8f, 0xed, 0x45, 0x36, 0x05, 0xd1, 0xb3, 0x17, 0xfc, 0xf8, 0x5b,
	0x78, 0x18, 0x3a, 0x1f, 0xe6, 0x6e, 0xe8, 0x70, 0xca, 0xd2, 0x1b, 0xbd, 0x2a, 0x4b, 0xf8, 0x3e,
	0x3f, 0x66, 0xfc, 0xc4, 0x6d, 0xf3, 0x57, 0x01, 0xa4, 0xa4, 0xf0, 0x26, 0x9f, 0x03, 0xd4, 0x86,
	0x22, 0x5b, 0xa3, 0x47, 0x6b, 0x2e, 0xd8, 0xbd, 0xc7, 0x37, 0x1f, 0xf2, 0x51, 0x3b, 0x82, 0xa2,
	0x42, 0xa7, 0x14, 0xad, 0xe5, 0xad, 0x57, 0x69, 0xfe, 0xb2, 0x09, 0xc0, 0x87, 0xd8, 0x73, 0x42,
	0x74, 0x0c, 0x5b, 0x7c, 0x77, 0x5d, 0x35, 0xfb, 0xe3, 0xd9, 0x7b, 0xf2, 0x89, 0x53, 0x1e, 0xdc,
	0x8f, 0x70, 0xff, 0x86, 0xf9, 0x0d, 0x42, 0xf4, 0x32, 0x6b, 0xb7, 0x66, 0xc8, 0x6f, 0x49, 0x9f,
	0x78, 0xf8, 0xef, 0x44, 0xdd, 0xe0, 0xe1, 0xd3, 0x63, 0xb7, 0xde, 0x43, 0xeb, 0xf5, 0x0f, 0xaf,
	0x2e, 0xdd, 0x78, 0x32, 0x1f, 0x1e, 0x8c, 0x02, 0xef, 0x70, 0x1c, 0x78, 0xae, 0x1f, 0x7c, 0xfd,
	0x0d, 0xfd, 0x5f, 0x60, 0x8d, 0x87, 0x56, 0xe4, 0x84, 0x1f, 0x9d, 0xf0, 0xf0, 0xfa, 0x5f, 0x85,
	0x61, 0x91, 0xfe, 0x45, 0x78, 0xf5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x51, 0xdc, 0xd6,
	0x45, 0x0c, 0x00, 0x00,
}
